(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 1160,
	height: 786,
	fps: 24,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.flechas1 = function() {
	this.spriteSheet = ss["Pag97_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.FONDOFLASH = function() {
	this.spriteSheet = ss["Pag97_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.Símbolo8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNANQgGgFAAgIQAAgHAGgGQAGgGAHAAQAIAAAGAGQAGAGAAAHQAAAIgGAFQgGAGgIABQgHgBgGgGg");
	this.shape.setTransform(373.5,76.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_1.setTransform(359.6,69.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAEBUIgEgBIgGABIgFABIghhVQgRgpgUgsIAJABIAJABIAIgBIAIgBQALAkANAiQAOAiANAjQAKgUAKgYIASguIASgxIAFABIAGABIAFgBIAGgBIgmBVQgTAqgPArIgGgBg");
	this.shape_2.setTransform(342.4,69.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAHB9IgHgBIgGABIgIABIACghIAAgiIAAgmIAAggIgCghIAIABIAGABIAHgBIAJgBQgCAQgBARIAAAgIAAAmIAAAiQABARACAQIgJgBgAgMheQgEgFgBgIQABgIAEgFQAFgFAHAAQAIAAAEAFQAFAFABAIQgBAIgFAFQgEAFgIABQgHgBgFgFg");
	this.shape_3.setTransform(329,65.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNBkQgLgMAAgWIABgdIABgkIABgtIgMAAIgMABIAAgFIABgEIgBgDIAAgEIAXABIAAgSIgBgWIAcgNIACAAIgCAbIgBAbIAPgBIAXgBIgBAFIAAADIAAAEIABAEIgVgBIgRAAIgBALIgBAZIgBAaIAAAbQAAAOABANQACAMAGAIQAGAHAOABIAIgBIAIgBIAAAIIgNAEIgOABQgUAAgMgLg");
	this.shape_4.setTransform(319.3,67.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAHB9IgHgBIgHABIgHABIACghIAAgiIAAgmIAAggIgCghIAHABIAHABIAHgBIAJgBQgCAQAAARIgBAgIAAAmIABAiQAAARACAQIgJgBgAgLheQgFgFgBgIQABgIAFgFQAFgFAGAAQAHAAAGAFQAEAFABAIQgBAIgEAFQgGAFgHABQgGgBgFgFg");
	this.shape_5.setTransform(309,65.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgjBVQgLgDgIgFIAEgMIADgOIAEAAQADAFAFAGQAGAGAJAEQAHAEALAAQAHAAAIgEQAIgEAFgHQAEgHABgLQAAgNgJgGQgJgHgMgDIgYgIQgMgFgJgHQgIgKAAgSQgBgQAIgMQAGgMAOgHQANgHASAAQANAAAJAEIARAGIgDAJIgEAJIgBAIIgEAAQgEgJgIgHQgIgGgMgBQgGAAgGADQgIAEgEAGQgFAHAAAKQABAOAIAHQAJAGAKAEIAaAIQAMAEAIAHQAJAJAAASQAAAOgIANQgHANgPAJQgPAIgRAAQgRAAgLgEg");
	this.shape_6.setTransform(297,69.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdBUQgQgEgMgLQgOgLgHgRQgIgRAAgYQAAgXAIgRQAHgRAOgLQAMgKAQgFQAPgFAOAAQAPAAAQAFQAPAFANAKQAMALAJARQAHARAAAXQAAAYgHARQgJARgMALQgNALgPAEQgQAFgPAAQgOAAgPgFgAgghBQgMALgFARQgFASAAATQAAAUAFASQAFARAMALQANALATABQAVgBAMgLQAMgLAGgRQAEgSAAgUQAAgTgEgSQgGgRgMgLQgMgLgVAAQgTAAgNALg");
	this.shape_7.setTransform(280,69.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag4CGIgJgBIgIABIgIABIACgeIABgmIAAgkIAAg4IAAglIgBglIgCgfIAIABIAIABIAJgBIAIgBIgCASIgBARIABAAQADgIAHgIQAIgJAMgHQAMgGAQgBQATAAARAKQAQAJALAUQAKATABAfQgBAfgLASQgLAUgSAKQgSAKgTAAQgSAAgOgJQgOgKgIgRIgBAAIAAAXIAAAkIABAmIACAeIgIgBgAAAh2QgRAAgMAKQgMAKgFARQgFASAAAUQAAAmANAQQAOATAYAAQARAAALgKQALgKAGgQQAFgRAAgWQAAgdgIgQQgHgQgLgGQgLgGgLAAIgCAAg");
	this.shape_8.setTransform(260.3,74.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_9.setTransform(231.1,69.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag6B6QgUgOgBgYQAAgNAGgKQAFgKAJgGQAJgGAKgDIAAgBQgLgDgGgIQgGgHAAgLQAAgGAEgGQAEgGAGgEQAGgEAGgBIAAgBQgRgIgJgNQgKgNAAgUQAAgTAKgNQAJgNAPgHQAQgGATAAIALAAIAQABIAPABIAKABIATgBIALgBIgBAIIABAHIgVgCIgTgBIgBABQALAGAHANQAHAMAAAOQgBAbgSAQQgRAPgdAAIgKgBIgKAAQgHAAgFAFQgFAEgBAIQAAAHAFAFQAFAEAMAAIATABIASAAQAhABAOANQAPANAAATQAAARgJARQgJARgTALQgTALgcAAQgjAAgTgNgAgpAvQgPAKAAAXQAAAQAHAKQAHAKAMAFQAMAEAPAAQANAAANgFQANgFAJgKQAIgLAAgQQAAgVgNgKQgNgJgbAAIgCAAQgYAAgPAJgAgihvQgLANAAAWQAAAXAKANQAKANAVAAQAMAAAIgHQAJgHAEgLQAFgMAAgNQgBgXgKgMQgLgMgQAAQgTABgLAMg");
	this.shape_10.setTransform(213.2,74.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgUBWIgHgBIgIABIgHABIABgiIAAgzIAAgKIAAghIgBgqIAHABIAIABIAHgBIAHgBIgBAVIgBAOIABAAQALgTAKgKQAMgKANABIAFAAIAGACQgCAEAAAJIAAAQIgDACQgCgCgFgCQgFgCgFAAQgMAAgIAHQgGAHgFALQgEALAAAOIAAAvIAAAeIABATIgHgBg");
	this.shape_11.setTransform(199.1,69.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_12.setTransform(183.1,69.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgRBUQgPgFgOgLQgMgKgHgRQgIgRgBgYQABgeANgTQANgUAVgKQAVgJAVAAQAVAAAPAFQAPAEAIAHIgFALIgDAMIgEAAQgDgGgHgGQgGgHgJgEQgJgEgMAAQgTAAgOAKQgNAKgHARQgFASAAAVQAAAkAPATQARATAbAAQAQAAAOgHQAPgIAJgKIADABIgCAIIgBAJQgLAJgQAHQgQAGgRAAQgOAAgPgFg");
	this.shape_13.setTransform(165,69.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_14.setTransform(137.1,69.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("ABABWIgIgBIgHABIgIABIACgoIABgoIAAgUQAAgagLgOQgKgOgSgBQgXABgMAPQgMAPAAAdIAAAcIABAiQAAASACAPIgIgBIgIgBIgIABIgIABIACghIAAgiIAAgjIAAgjIgCghIAIABIAIABIAGgBIAIgBIgBAPIAAAOIABAAQAKgPAOgJQAOgIARAAQAOAAANAFQANAFAJAOQAJAOAAAYIgBAeIAAAjIAAAXIAAAXIgHgBg");
	this.shape_15.setTransform(118,69.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag3BIQgQgQAAgcIABgeIAAgbIAAgcIgBgdIAIABIAHAAIAHAAIAIgBIgCAvIgBAzQgBASAEAKQADAKAEAFQAFAGAIAEQAIADAKABQAOgBAKgGQAKgGAFgKIAEgLIACgMIABgTIAAgfIAAgfIAAgcIAHABIAHAAIAIAAIAHgBIgCA2IAAA1IAAAgIABAfIgHgCIgHAAIgHAAIgHACIABgQIAAgPIgBAAQgJAQgPAJQgPAJgPAAQgcAAgQgPg");
	this.shape_16.setTransform(98,69.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgjBOQgTgLgMgTQgKgTgBgYQAAgcAKgVQAJgVASgLQATgMAYAAQAaAAARAKQAQAKAIARQAIAQAAAUIAAAHIgBAHIgmAAIgmgBIgXABIgXAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAPgHQAOgHAKgLIACABIgCARQgLAJgRAHQgQAGgQAAQgYAAgUgLgAgWhCQgLAKgFAOQgGAOAAAOIAXAAIAWABIAYgBIAXAAQABgKgCgLQgCgLgFgJQgEgJgJgGQgJgGgOAAQgQAAgKAKg");
	this.shape_17.setTransform(69.1,69.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("ABABWIgIgBIgHABIgIABIACgoIABgoIAAgUQAAgagLgOQgKgOgSgBQgXABgMAPQgMAPAAAdIAAAcIABAiQAAASACAPIgIgBIgIgBIgIABIgIABIACghIAAgiIAAgjIAAgjIgCghIAIABIAIABIAGgBIAIgBIgBAPIAAAOIABAAQAKgPAOgJQAOgIARAAQAOAAANAFQANAFAJAOQAJAOAAAYIgBAeIAAAjIAAAXIAAAXIgHgBg");
	this.shape_18.setTransform(50,69.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgjBOQgUgLgLgTQgLgTAAgYQAAgcAKgVQAKgVARgLQATgMAYAAQAZAAASAKQAQAKAIARQAIAQAAAUIAAAHIgBAHIgmAAIgmgBIgXABIgXAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAPgHQAPgHAJgLIACABIgCARQgMAJgQAHQgPAGgRAAQgZAAgTgLgAgWhCQgLAKgFAOQgGAOAAAOIAXAAIAWABIAYgBIAXAAQABgKgCgLQgCgLgFgJQgEgJgJgGQgJgGgOAAQgPAAgLAKg");
	this.shape_19.setTransform(31.1,69.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAIB9IgIgBIgHABIgIABIACghIABgiIAAgmIgBggIgCghIAIABIAHABIAIgBIAIgBQgCAQgBARIAAAgIAAAmIAAAiQABARACAQIgIgBgAgMheQgFgFAAgIQAAgIAFgFQAFgFAHAAQAHAAAFAFQAGAFAAAIQAAAIgGAFQgFAFgHABQgHgBgFgFg");
	this.shape_20.setTransform(17,65.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgMBkQgMgMAAgWIABgdIACgkIABgtIgNAAIgMABIAAgFIABgEIgBgDIAAgEIAYABIgBgSIgBgWIAcgNIACAAIgCAbIgBAbIAOgBIAYgBIAAAFIAAADIAAAEIAAAEIgUgBIgSAAIgBALIgBAZIgBAaIAAAbQAAAOABANQACAMAGAIQAHAHAOABIAHgBIAIgBIAAAIIgNAEIgOABQgVAAgKgLg");
	this.shape_21.setTransform(7.3,67.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAHCGIgHAAIgHAAIgIACIACgfIABglIAAgkIAAg/IAAgkIgBgmIgCgeIAIABIAHABIAHgBIAJgBIgCAeIgBAmIAAAkIAAA/IAAAkIABAlIACAfIgJgCg");
	this.shape_22.setTransform(494.5,21.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_23.setTransform(480.6,26.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgMBkQgMgMAAgWIABgcIACglIABgtIgNAAIgMABIAAgFIAAgDIAAgEIAAgEIAYABIgBgSIgBgWIAcgNIACAAIgCAbIgBAbIAOgBIAYgBIAAAEIAAAFIAAADIAAAEIgUgBIgSAAIgBAMIgBAYIgBAbIAAAbQAAANABANQACAMAGAIQAGAHAPABIAHgBIAIgBIAAAIIgNAEQgHACgHgBQgVABgKgMg");
	this.shape_24.setTransform(466.8,24.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgjBOQgUgLgLgTQgKgTgBgYQAAgcAKgVQAJgVATgLQASgMAZAAQAZAAAQAKQARAKAIARQAIAQAAAUIAAAHIAAAHIgnAAIgngBIgVABIgYAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAOgHQAPgHAKgLIACABIgCARQgMAJgPAHQgQAGgSAAQgYAAgTgLgAgWhCQgLAKgFAOQgFAOgBAOIAXAAIAWABIAYgBIAYAAQAAgKgCgLQgCgLgEgJQgFgJgJgGQgJgGgNAAQgQAAgLAKg");
	this.shape_25.setTransform(452.6,26.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AB0BWIgIgBIgJABIgHABIACglQABgdABgtQAAgTgJgMQgIgMgVAAQgNAAgKAEQgJAGgEAGIgFAIIgCAMIgCAWIAAAnIAAATIABASIABAUIgIgBIgHgBIgHABIgIABIADgpIABgpIgBgYIAAgQIgDgJIgDgHQgFgHgHgFQgJgFgJABQgXAAgLAPQgMAPAAAcIAAAdIABAiIACAhIgIgBIgIgBIgJABIgIABIACghIABgiIAAgjIgBgiIgCgiIAIABIAJABIAGgBIAIgBIgBAPIAAAOIABAAQAJgQANgIQAOgIARAAQAMAAALAEQALAFAGAIQAHAIADAKIABAAQAJgRAPgJQAPgJAUAAQAPAAAMAFQANAGAHAMQAHANABAUIgBATIgBAXIgBAkIABATIAAAUIgHgBg");
	this.shape_26.setTransform(428.5,26.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAHCGIgHAAIgHAAIgIACIACgfIABglIAAgkIAAg/IAAgkIgBgmIgCgeIAIABIAHABIAHgBIAJgBIgCAeIgBAmIAAAkIAAA/IAAAkIABAlIACAfIgJgCg");
	this.shape_27.setTransform(398.5,21.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgjBOQgTgLgMgTQgKgTgBgYQAAgcAKgVQAJgVASgLQATgMAYAAQAaAAARAKQAQAKAIARQAIAQAAAUIAAAHIgBAHIgmAAIgmgBIgXABIgXAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAPgHQAOgHAKgLIACABIgCARQgLAJgRAHQgQAGgQAAQgYAAgUgLgAgWhCQgLAKgFAOQgGAOAAAOIAXAAIAWABIAYgBIAXAAQABgKgCgLQgCgLgFgJQgEgJgJgGQgJgGgOAAQgQAAgKAKg");
	this.shape_28.setTransform(384.6,26.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgjBOQgUgLgLgTQgLgTAAgYQAAgcAKgVQAKgVARgLQATgMAYAAQAZAAASAKQAQAKAIARQAIAQAAAUIAAAHIgBAHIgmAAIgmgBIgWABIgYAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAPgHQAPgHAJgLIACABIgCARQgMAJgQAHQgPAGgRAAQgZAAgTgLgAgWhCQgLAKgFAOQgGAOAAAOIAXAAIAWABIAYgBIAXAAQABgKgCgLQgCgLgFgJQgEgJgJgGQgJgGgOAAQgPAAgLAKg");
	this.shape_29.setTransform(346.6,26.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("Ag3BIQgQgQgBgcIABgeIABgbIgBgcIAAgdIAIABIAHAAIAIAAIAHgBIgDAvIgBAzQABASADAKQADAKAEAFQAFAGAJAEQAHADALABQANgBAKgGQAKgGAEgKIAFgLIACgMIABgTIAAgfIAAgfIgBgcIAIABIAIAAIAIAAIAGgBIgCA2IAAA1IAAAgIABAfIgHgCIgHAAIgHAAIgHACIABgQIAAgPIgBAAQgJAQgPAJQgOAJgQAAQgdAAgPgPg");
	this.shape_30.setTransform(327.5,26.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("ABKCGIgIgBIgIABIgIABIABgeIABgmIAAgkIAAgbIAAAAQgLAUgPAKQgPAKgQAAQgSAAgSgJQgRgIgLgUQgLgRgBghQABgfALgUQALgUASgKQARgKASAAQAWABAOALQAPAKAGARIAAAAIAAgRIgCgSIAIABIAIABIAIgBIAIgBIgCAfIgBAlIAAAlIAAA4IAAAkIABAmIACAeIgIgBgAgVhwQgMAHgIARQgIARAAAfQAAAVAFAQQAGAOAKAKQALAJAQAAQAQAAANgMQAMgLAGgQQAGgSAAgVQABgSgGgQQgFgQgMgKQgLgKgSAAIgBAAQgKAAgLAGg");
	this.shape_31.setTransform(307.2,31.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgjBVQgMgDgHgFIAEgMIADgOIAEAAQADAFAFAGQAGAGAJAEQAHAEALAAQAHAAAIgEQAIgEAEgHQAFgHABgLQAAgNgJgGQgJgHgMgDIgYgIQgMgFgJgHQgIgKgBgSQAAgQAIgMQAGgMAOgHQANgHASAAQANAAAJAEIARAGIgDAJIgEAJIgBAIIgEAAQgDgJgIgHQgJgGgMgBQgGAAgGADQgIAEgEAGQgEAHgBAKQABAOAIAHQAJAGAKAEIAZAIQANAEAIAHQAJAJAAASQAAAOgIANQgHANgPAJQgOAIgTAAQgQAAgLgEg");
	this.shape_32.setTransform(280.5,26.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_33.setTransform(264.6,26.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgUBWIgHgBIgIABIgHABIABgiIAAgzIAAgLIAAggIgBgqIAHABIAIABIAHgBIAHgBIgBAVIgBAOIABABQALgUAKgJQAMgKANAAIAFAAIAGACQgCAFAAAIIAAAQIgDACQgCgCgFgCQgFgCgFAAQgMABgIAGQgGAHgFAKQgEAMAAAOIAAAwIAAAdIABATIgHgBg");
	this.shape_34.setTransform(251,26.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgNBkQgLgMAAgWIABgcIABglIABgtIgLAAIgNABIAAgFIABgDIgBgEIAAgEIAXABIAAgSIgBgWIAcgNIACAAIgCAbIgBAbIAPgBIAXgBIgBAEIAAAFIAAADIABAEIgVgBIgRAAIgBAMIgBAYIgBAbIAAAbQAAANABANQACAMAHAIQAFAHAOABIAIgBIAIgBIAAAIIgNAEQgHACgHgBQgUABgMgMg");
	this.shape_35.setTransform(239.2,24.5);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("ABABWIgIgBIgHABIgIABIACgnIABgpIAAgUQAAgbgLgOQgKgOgSABQgXAAgMAPQgMAPAAAcIAAAdIABAiQAAARACAQIgIgBIgIgBIgIABIgIABIACghIAAgiIAAgjIAAgiIgCgiIAIABIAIABIAGgBIAIgBIgBAPIAAAOIABAAQAKgPAOgJQAOgIARAAQAOgBANAGQANAFAJAOQAJANAAAZIgBAeIAAAjIAAAXIAAAXIgHgBg");
	this.shape_36.setTransform(223.9,26.5);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgjBOQgTgLgMgTQgKgTgBgYQAAgcAKgVQAJgVASgLQATgMAYAAQAaAAARAKQAQAKAIARQAIAQAAAUIAAAHIgBAHIgmAAIgmgBIgXABIgXAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAPgHQAOgHAKgLIACABIgCARQgLAJgRAHQgQAGgQAAQgYAAgUgLgAgWhCQgLAKgFAOQgGAOAAAOIAXAAIAWABIAYgBIAXAAQABgKgCgLQgCgLgFgJQgEgJgJgGQgJgGgOAAQgQAAgKAKg");
	this.shape_37.setTransform(205,26.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAHB9IgHgBIgHABIgIABIADghIAAgiIAAgmIAAggIgDghIAIABIAHABIAHgBIAJgBQgCAQAAARIgBAgIAAAmIABAiQAAARACAQIgJgBgAgLheQgGgFAAgIQAAgIAGgFQAFgFAGAAQAHAAAGAFQAFAFAAAIQAAAIgFAFQgGAFgHABQgGgBgFgFg");
	this.shape_38.setTransform(190.9,22.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("ABzBWIgHgBIgIABIgIABIACglQACgdgBgtQABgTgJgMQgJgMgUAAQgNAAgKAEQgIAGgFAGIgFAIIgDAMIgBAWIAAAnIAAATIABASIABAUIgJgBIgGgBIgHABIgIABIADgpIAAgpIAAgYIAAgQIgCgJIgEgHQgFgHgHgFQgJgFgJABQgXAAgMAPQgLAPAAAcIAAAdIABAiIABAhIgIgBIgIgBIgIABIgHABIACghIAAgiIAAgjIAAgiIgCgiIAHABIAIABIAHgBIAIgBIgBAPIAAAOIABAAQAJgQANgIQAOgIARAAQANAAAKAEQALAFAGAIQAHAIAEAKIAAAAQAJgRAPgJQAPgJATAAQAQAAAMAFQANAGAHAMQAHANAAAUIgBATIgBAXIAAAkIAAATIABAUIgIgBg");
	this.shape_39.setTransform(171,26.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,511.7,89.8);


(lib.Símbolo7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgbAxIAbhVQAAgGAEgDQADgFAIAAQAEAAAEACQAFAEAAAGIgBAIIgFAHIgrBLg");
	this.shape.setTransform(135.3,127.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_1.setTransform(122.5,118.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAEBUIgEAAIgGAAIgFACIghhWQgRgpgUgrIAJABIAJAAIAIAAIAIgBQALAiANAjQAOAiANAiQAKgTAKgYIASguIASgwIAFABIAGAAIAFAAIAGgBIgmBUQgTArgQArIgFgCg");
	this.shape_2.setTransform(105.2,118.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAHB9IgHgBIgGABIgIABIABghIABgiIAAgmIgBggIgBghIAIABIAGABIAHgBIAJgBQgCAQgBARIAAAgIAAAmIAAAiQABARACAQIgJgBgAgMheQgEgFgBgIQABgIAEgFQAFgFAHAAQAIAAAFAFQAEAFABAIQgBAIgEAFQgFAFgIABQgHgBgFgFg");
	this.shape_3.setTransform(91.9,114);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNBjQgLgMABgUIAAgeIABgkIABgtIgMAAIgMABIAAgEIABgFIgBgDIAAgDIAXABIAAgSIgBgXIAcgMIACAAIgCAaIgBAbIAPAAIAXgBIgBAEIAAADIAAAEIABAEIgVgBIgRAAIgBALIgBAYIgBAbIAAAbQAAAOABAMQACANAGAIQAGAIAOAAIAIgBIAIgCIAAAJIgNAEIgOACQgUAAgMgNg");
	this.shape_4.setTransform(82.2,115.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_5.setTransform(68,118.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag6B6QgUgOgBgYQAAgNAGgKQAFgKAJgGQAJgGAKgDIAAgBQgLgDgGgIQgGgHAAgLQAAgGAEgGQAEgGAGgEQAGgEAGgBIAAgBQgRgIgJgNQgKgNAAgUQAAgTAKgNQAJgNAPgHQAQgGATAAIALAAIAQABIAPABIAKABIATgBIALgBIgBAIIABAHIgVgCIgTgBIgBABQALAGAHANQAHAMAAAOQgBAbgSAQQgRAPgdAAIgKgBIgKAAQgHAAgFAFQgFAEgBAIQAAAHAFAFQAFAEAMAAIATABIASAAQAhABAOANQAPANAAATQAAARgJARQgJARgTALQgTALgcAAQgjAAgTgNgAgpAvQgPAKAAAXQAAAQAHAKQAHAKAMAFQAMAEAPAAQANAAANgFQANgFAJgKQAIgLAAgQQAAgVgNgKQgNgJgbAAIgCAAQgYAAgPAJgAgihvQgLANAAAWQAAAXAKANQAKANAVAAQAMAAAIgHQAJgHAEgLQAFgMAAgNQgBgXgKgMQgLgMgQAAQgTABgLAMg");
	this.shape_6.setTransform(50.1,122.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgjBOQgTgLgMgTQgLgTAAgYQAAgcAKgVQAKgVARgLQATgMAYAAQAaAAAQAKQARAKAIARQAIAQAAAUIAAAHIAAAHIgnAAIgngBIgWABIgXAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAPgHQAPgHAJgLIACABIgCARQgMAJgPAHQgRAGgRAAQgXAAgUgLgAgWhCQgLAKgFAOQgFAOgBAOIAXAAIAWABIAYgBIAXAAQABgKgCgLQgBgLgFgJQgFgJgJgGQgJgGgNAAQgRAAgKAKg");
	this.shape_7.setTransform(32,118.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("ABABWIgIAAIgHAAIgIACIACgpIABgoIAAgUQAAgagLgOQgKgPgSAAQgXAAgMAQQgMAPAAAdIAAAcIABAiQAAASACAQIgIgCIgIAAIgIAAIgIACIACgiIAAgiIAAgkIAAgiIgCggIAIABIAIAAIAGAAIAIgBIgBAOIAAAOIABAAQAKgQAOgIQAOgIARgBQAOABANAFQANAFAJAOQAJANAAAZIgBAeIAAAjIAAAXIAAAYIgHgCg");
	this.shape_8.setTransform(12.9,117.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_9.setTransform(490.7,73);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag6B6QgUgOgBgYQAAgNAGgKQAFgKAJgGQAJgGAKgDIAAgBQgLgDgGgIQgGgHAAgLQAAgGAEgGQAEgGAGgEQAGgEAGgBIAAgBQgRgIgJgNQgKgNAAgUQAAgTAKgNQAJgNAPgHQAQgGATAAIALAAIAQABIAPABIAKABIATgBIALgBIgBAIIABAHIgVgCIgTgBIgBABQALAGAHANQAHAMAAAOQgBAbgSAQQgRAPgdAAIgKgBIgKAAQgHAAgFAFQgFAEgBAIQAAAHAFAFQAFAEAMAAIATABIASAAQAhABAOANQAPANAAATQAAARgJARQgJARgTALQgTALgcAAQgjAAgTgNgAgpAvQgPAKAAAXQAAAQAHAKQAHAKAMAFQAMAEAPAAQANAAANgFQANgFAJgKQAIgLAAgQQAAgVgNgKQgNgJgbAAIgCAAQgYAAgPAJgAgihvQgLANAAAWQAAAXAKANQAKANAVAAQAMAAAIgHQAJgHAEgLQAFgMAAgNQgBgXgKgMQgLgMgQAAQgTABgLAMg");
	this.shape_10.setTransform(472.8,77.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgUBWIgHgBIgIABIgHACIABgjIAAg0IAAgJIAAghIgBgpIAHABIAIAAIAHAAIAHgBIgBAUIgBAOIABAAQALgTAKgKQAMgKANAAIAFABIAGACQgCAFAAAIIAAAQIgDACQgCgDgFgBQgFgCgFAAQgMABgIAGQgGAHgFALQgEALAAAOIAAAvIAAAfIABATIgHgCg");
	this.shape_11.setTransform(458.7,72.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_12.setTransform(442.7,73);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgRBUQgQgFgMgLQgNgKgHgRQgIgRAAgYQAAgeANgTQANgUAVgKQAVgJAVAAQAUAAAQAFQAPAEAIAHIgFALIgDAMIgEAAQgDgGgHgGQgGgHgJgEQgJgEgMAAQgTAAgOAKQgNAKgHARQgFASgBAVQAAAkAQATQAQATAcAAQAPAAAPgHQAPgIAJgKIADABIgCAIIgBAJQgLAJgQAHQgQAGgRAAQgOAAgPgFg");
	this.shape_13.setTransform(424.6,73);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_14.setTransform(356.7,73);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("ABABWIgIgBIgHABIgIACIACgpIABgoIAAgUQAAgagLgOQgKgOgSgBQgXAAgMAQQgMAPAAAdIAAAcIABAiQAAARACARIgIgCIgIgBIgIABIgIACIACgiIAAgiIAAgkIAAgiIgCggIAIABIAIAAIAGAAIAIgBIgBAOIAAAOIABAAQAKgQAOgIQAOgIARgBQAOABANAFQANAFAJAOQAJANAAAZIgBAeIAAAjIAAAXIAAAYIgHgCg");
	this.shape_15.setTransform(337.6,72.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag3BIQgQgQgBgcIABgeIABgbIgBgcIAAgdIAIABIAHAAIAIAAIAHgBIgDAvIgBAzQABASADAKQADAKAEAFQAFAGAJAEQAHADALABQANgBAKgGQAKgGAEgKIAFgLIACgMIABgTIAAgfIAAgfIgBgcIAIABIAIAAIAIAAIAGgBIgCA2IAAA1IAAAgIABAfIgHgCIgHAAIgHAAIgHACIABgQIAAgPIgBAAQgJAQgPAJQgOAJgQAAQgdAAgPgPg");
	this.shape_16.setTransform(317.6,73.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgjBOQgTgLgMgTQgLgTAAgYQAAgcAKgVQAJgVASgLQATgMAYAAQAaAAARAKQAQAKAIARQAIAQAAAUIAAAHIgBAHIgmAAIgmgBIgXABIgXAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAPgHQAOgHAKgLIACABIgCARQgLAJgRAHQgQAGgQAAQgYAAgUgLgAgWhCQgLAKgFAOQgGAOAAAOIAXAAIAWABIAYgBIAXAAQABgKgCgLQgBgLgGgJQgEgJgJgGQgJgGgOAAQgQAAgKAKg");
	this.shape_17.setTransform(238.7,73);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgjBOQgTgLgMgTQgLgTAAgYQAAgcAKgVQAJgVASgLQATgMAYAAQAaAAARAKQAQAKAIARQAIAQAAAUIAAAHIgBAHIgmAAIgmgBIgXABIgXAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAPgHQAOgHAKgLIACABIgCARQgLAJgRAHQgQAGgQAAQgYAAgUgLgAgWhCQgLAKgFAOQgGAOAAAOIAXAAIAWABIAYgBIAXAAQABgKgCgLQgBgLgGgJQgEgJgJgGQgJgGgOAAQgQAAgKAKg");
	this.shape_18.setTransform(220.7,73);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgjBVQgLgDgIgFIAEgMIADgOIAEAAQADAFAGAGQAFAGAIAEQAJAEAKAAQAHAAAIgEQAHgEAGgHQAFgHAAgLQgBgNgIgGQgJgHgMgDIgYgIQgMgFgIgHQgJgKAAgSQgBgQAIgMQAGgMAOgHQANgHARAAQAOAAAJAEIASAGIgFAJIgDAJIgBAIIgFAAQgCgJgJgHQgIgGgMgBQgFAAgIADQgGAEgFAGQgFAHAAAKQAAAOAJAHQAJAGAKAEIAaAIQAMAEAIAHQAJAJAAASQAAAOgIANQgHANgPAJQgPAIgRAAQgRAAgLgEg");
	this.shape_19.setTransform(204.6,73);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgeBUQgPgEgNgLQgNgLgHgRQgHgRgBgYQABgXAHgRQAHgRANgLQANgKAPgFQAQgFAOAAQAQAAAPAFQAPAFANAKQAMALAJARQAHARAAAXQAAAYgHARQgJARgMALQgNALgPAEQgPAFgQAAQgOAAgQgFgAgghBQgMALgFARQgGASABATQgBAUAGASQAFARAMALQAMALAUABQAVgBAMgLQAMgLAGgRQAEgSAAgUQAAgTgEgSQgGgRgMgLQgMgLgVAAQgUAAgMALg");
	this.shape_20.setTransform(187.6,73);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("Ag4CGIgJgBIgIABIgIABIACgeIABgmIAAgkIAAg4IAAglIgBglIgCgfIAIABIAIABIAJgBIAIgBIgCASIgBARIABAAQADgIAHgIQAIgJAMgHQAMgGAQgBQATAAARAKQAQAJALAUQAKATABAfQgBAfgLASQgLAUgSAKQgSAKgTAAQgSAAgOgJQgOgKgIgRIgBAAIAAAXIAAAkIABAmIACAeIgIgBgAAAh2QgRAAgMAKQgMAKgFARQgFASAAAUQAAAmANAQQAOATAYAAQARAAALgKQALgKAGgQQAFgRAAgWQAAgdgIgQQgHgQgLgGQgLgGgLAAIgCAAg");
	this.shape_21.setTransform(167.8,77.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAHCGIgHAAIgHAAIgIACIACgfIABglIAAgkIAAg/IAAgkIgBgmIgCgeIAIABIAHABIAHgBIAJgBIgCAeIgBAmIAAAkIAAA/IAAAkIABAlIACAfIgJgCg");
	this.shape_22.setTransform(102.6,68);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_23.setTransform(88.7,73);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgRBUQgPgFgNgLQgNgKgIgRQgHgRAAgYQAAgeANgTQAOgUAUgKQAVgJAWAAQATAAAQAFQAQAEAGAHIgEALIgEAMIgDAAQgDgGgGgGQgHgHgJgEQgJgEgLAAQgUAAgOAKQgOAKgFARQgHASAAAVQABAkAQATQAQATAbAAQAQAAAOgHQAPgIAJgKIACABIgBAIIgBAJQgLAJgQAHQgQAGgRAAQgOAAgPgFg");
	this.shape_24.setTransform(70.6,73);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAHB9IgHgBIgHABIgHABIACghIAAgiIAAgmIAAggIgCghIAHABIAHABIAHgBIAJgBQgCAQAAARIgBAgIAAAmIABAiQAAARACAQIgJgBgAgLheQgFgFgBgIQABgIAFgFQAFgFAGAAQAHAAAGAFQAEAFABAIQgBAIgEAFQgGAFgHABQgGgBgFgFg");
	this.shape_25.setTransform(56.6,68.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgrCBQgQgKgLgUQgKgTgBgfQABgfALgSQALgUASgKQASgKATAAQASAAAOAKQAOAIAHASIABAAIAAgwIAAgvIgBglIAIABIAIAAIAHAAIAJgBIgCAhIgBAwIgBA2IAAAxIAAAsIABAqIgIgCIgGAAIgHAAIgHACIABgkIgBAAQgDAIgIAJQgHAKgNAGQgMAGgQABQgSgBgRgIgAgbgOQgLAKgGAQQgFARAAAWQAAAdAIAQQAHAPALAHQAMAGALAAQARAAAMgMQAMgLAGgTQAGgSgBgUQAAgigNgRQgNgSgaAAQgPAAgMALg");
	this.shape_26.setTransform(41.3,68.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_27.setTransform(22.7,73);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgUBWIgHgBIgIABIgHACIABgjIAAg0IAAgJIAAghIgBgpIAHABIAIAAIAHAAIAHgBIgBAUIgBAOIABAAQALgTAKgKQAMgKANAAIAFABIAGACQgCAFAAAIIAAAQIgDACQgCgDgFgBQgFgCgFAAQgMABgIAGQgGAHgFALQgEALAAAOIAAAvIAAAfIABATIgHgCg");
	this.shape_28.setTransform(9.1,72.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAhB6IgIAAIgJAAIgIACIACgvIABguIAAh+IgpAYQgCgEgDgDIgGgFIAAgCIApgTIAngTIADACIgCAvIgBAvIAAA6IABAuIACAvIgJgCg");
	this.shape_29.setTransform(489.6,22.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgsALIAAgVIBYAAIAAAVg");
	this.shape_30.setTransform(476,26.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("ABiB6IgJAAIgIAAIgJACIACgvIABgvIAAgeIgmgBIglAAIgkAAIglABIAAAeIAAAvIACAvIgJgCIgJAAIgIAAIgJACIACgvIABgvIAAg8IgBguIgCgvIAJABIAIABIAJgBIAJgBIgCAvIAAAuIAAANIAlABIAkAAIAlAAIAmgBIAAgNIgBguIgCgvIAJABIAIABIAJgBIAJgBIgCAvIAAAuIAAA8IAAAvIACAvIgJgCg");
	this.shape_31.setTransform(456,22.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AhFBxQgegPgRgcQgRgdAAgpQAAgnARgdQARgdAegPQAfgPAmAAQAnAAAfAPQAeAPARAdQARAdABAnQgBApgRAdQgRAcgeAPQgfAPgnAAQgmAAgfgPgAAyBnQAXgMANgaQANgZAAgoQAAgmgNgaQgNgagXgMQgXgMgbAAQgbAAgXAMQgWAMgNAaQgNAaAAAmQAAAoANAZQANAaAWAMQAXAMAbAAQAbAAAXgMg");
	this.shape_32.setTransform(427,22.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgbAxIAbhWQAAgEAEgFQAEgEAHgBQAFABAEADQAEADAAAGIgCAIIgDAHIgrBKg");
	this.shape_33.setTransform(365.9,36.2);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgeBUQgPgEgNgLQgMgLgIgRQgHgRgBgYQABgXAHgRQAIgRAMgLQANgKAPgFQAPgFAPAAQAPAAAQAFQAQAFAMAKQANALAHARQAIARAAAXQAAAYgIARQgHARgNALQgMALgQAEQgQAFgPAAQgPAAgPgFgAgfhBQgNALgFARQgFASAAATQAAAUAFASQAFARANALQAMALATABQAVgBAMgLQAMgLAFgRQAGgSAAgUQAAgTgGgSQgFgRgMgLQgMgLgVAAQgTAAgMALg");
	this.shape_34.setTransform(352,26.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgMBkQgMgMAAgWIABgcIACglIABgtIgNAAIgNABIABgFIAAgDIAAgEIgBgEIAZABIgBgSIgBgWIAcgNIABAAIgBAbIgBAbIAOgBIAYgBIAAAEIAAAFIAAADIAAAEIgUgBIgSAAIgBAMIgBAYIgBAbIAAAbQAAANACANQABAMAGAIQAHAHAOABIAIgBIAHgBIAAAIIgNAEQgHACgHgBQgVABgKgMg");
	this.shape_35.setTransform(337.3,24.5);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAIB9IgIgBIgGABIgIABIABghIABgiIAAgmIgBggIgBghIAIABIAGABIAIgBIAIgBQgCAQgBARIAAAgIAAAmIAAAiQABARACAQIgIgBgAgMheQgFgFAAgIQAAgIAFgFQAGgFAGAAQAHAAAFAFQAGAFAAAIQAAAIgGAFQgFAFgHABQgGgBgGgFg");
	this.shape_36.setTransform(327,22.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgkBVQgKgDgIgFIAFgMIACgOIAEAAQACAFAGAGQAGAGAJAEQAIAEAKAAQAHAAAIgEQAIgEAEgHQAGgHAAgLQgBgNgIgGQgIgHgNgDIgXgIQgNgFgJgHQgIgKgBgSQABgQAGgMQAIgMANgHQAOgHAQAAQANAAAKAEIASAGIgFAJIgCAJIgCAIIgFAAQgDgJgHgHQgJgGgMgBQgFAAgIADQgGAEgFAGQgEAHgBAKQABAOAIAHQAIAGALAEIAZAIQANAEAJAHQAIAJAAASQAAAOgHANQgJANgOAJQgOAIgTAAQgQAAgMgEg");
	this.shape_37.setTransform(315,26.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgeCBQgPgFgNgLQgMgKgIgRQgHgSgBgXQABgZAHgRQAIgPAMgLQANgKAPgGQAPgEAPAAQAPAAAQAEQAQAGAMAKQANALAHAPQAIARAAAZQAAAXgIASQgHARgNAKQgMALgQAFQgQAFgPAAQgPAAgPgFgAgfgVQgNAMgFAPQgFASAAAVQAAAUAFASQAFARANALQAMALATAAQAVAAAMgLQAMgLAFgRQAGgSAAgUQAAgVgGgSQgFgPgMgMQgMgLgVAAQgTAAgMALgAgXhGIAzg2IAIgHQAEgCAFAAQADAAAEADQAEADAAAFQAAAHgEAEQgEAEgFADIgzAig");
	this.shape_38.setTransform(298,22.2);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("Ag4CGIgJgBIgIABIgIABIACgeIABgmIAAgkIAAg4IAAglIgBglIgCgfIAIABIAIABIAJgBIAIgBIgCASIgBARIABAAQADgIAHgIQAIgJAMgHQAMgGAQgBQATAAARAKQAQAJALAUQAKATABAfQgBAfgLASQgLAUgSAKQgSAKgTAAQgSAAgOgJQgOgKgIgRIgBAAIAAAXIAAAkIABAmIACAeIgIgBgAAAh2QgRAAgMAKQgMAKgFARQgFASAAAUQAAAmANAQQAOATAYAAQARAAALgKQALgKAGgQQAFgRAAgWQAAgdgIgQQgHgQgLgGQgLgGgLAAIgCAAg");
	this.shape_39.setTransform(278.2,31.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgdBUQgQgEgMgLQgOgLgHgRQgIgRAAgYQAAgXAIgRQAHgRAOgLQAMgKAQgFQAPgFAOAAQAPAAAQAFQAPAFANAKQAMALAIARQAIARAAAXQAAAYgIARQgIARgMALQgNALgPAEQgQAFgPAAQgOAAgPgFgAgghBQgMALgFARQgFASAAATQAAAUAFASQAFARAMALQANALATABQAVgBAMgLQAMgLAGgRQAEgSAAgUQAAgTgEgSQgGgRgMgLQgMgLgVAAQgTAAgNALg");
	this.shape_40.setTransform(258,26.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgUBWIgHgBIgIABIgHABIABgiIAAgzIAAgLIAAggIgBgqIAHABIAIABIAHgBIAHgBIgBAVIgBAOIABABQALgUAKgJQAMgKANAAIAFAAIAGACQgCAFAAAIIAAAQIgDACQgCgCgFgCQgFgCgFAAQgMABgIAGQgGAHgFAKQgEAMAAAOIAAAwIAAAdIABATIgHgBg");
	this.shape_41.setTransform(243.1,26.5);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("Ag4CGIgJgBIgIABIgIABIACgeIABgmIAAgkIAAg4IAAglIgBglIgCgfIAIABIAIABIAJgBIAIgBIgCASIgBARIABAAQADgIAHgIQAIgJAMgHQAMgGAQgBQATAAARAKQAQAJALAUQAKATABAfQgBAfgLASQgLAUgSAKQgSAKgTAAQgSAAgOgJQgOgKgIgRIgBAAIAAAXIAAAkIABAmIACAeIgIgBgAAAh2QgRAAgMAKQgMAKgFARQgFASAAAUQAAAmANAQQAOATAYAAQARAAALgKQALgKAGgQQAFgRAAgWQAAgdgIgQQgHgQgLgGQgLgGgLAAIgCAAg");
	this.shape_42.setTransform(226.2,31.2);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("ABoB9IgKgBIgJABIgKABQgDgNgGgQIgOgiIgOghIgXgBIgWAAIgWAAIgWABIgUA1QgKAagEARIgIgBIgGgBIgGABIgHABIA4h+IA4h9IAFAAIAXA3IAZA7IAYA3IAVAxIAPAhIgJgBgAgsANIAUAAIATABIASAAIAUgBIgmhZg");
	this.shape_43.setTransform(164,22.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,514.2,138.3);


(lib.Símbolo6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNAOQgGgGAAgIQAAgHAGgGQAGgGAHAAQAIAAAGAGQAGAGAAAHQAAAIgGAGQgGAFgIABQgHgBgGgFg");
	this.shape.setTransform(112.6,77.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAHCGIgHAAIgHAAIgIACIACgfIABglIAAgkIAAg/IAAgkIgBgmIgCgeIAIABIAHABIAHgBIAJgBIgCAeIgBAmIAAAkIAAA/IAAAkIABAlIACAfIgJgCg");
	this.shape_1.setTransform(102.6,65.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_2.setTransform(88.7,70.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgRBUQgPgFgNgLQgNgKgIgRQgHgRAAgYQAAgeANgTQAOgUAUgKQAVgJAWAAQATAAAQAFQAQAEAGAHIgEALIgEAMIgDAAQgDgGgGgGQgHgHgJgEQgJgEgLAAQgUAAgOAKQgOAKgFARQgHASAAAVQABAkAQATQAQATAbAAQAQAAAOgHQAPgIAJgKIACABIgBAIIgBAJQgLAJgQAHQgQAGgRAAQgOAAgPgFg");
	this.shape_3.setTransform(70.6,70.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAHB9IgHgBIgHABIgHABIACghIAAgiIAAgmIAAggIgCghIAHABIAHABIAHgBIAJgBQgCAQAAARIgBAgIAAAmIABAiQAAARACAQIgJgBgAgLheQgFgFgBgIQABgIAFgFQAFgFAGAAQAHAAAGAFQAEAFABAIQgBAIgEAFQgGAFgHABQgGgBgFgFg");
	this.shape_4.setTransform(56.6,66.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgrCAQgQgJgLgTQgKgUgBgfQABgeALgTQALgUASgKQASgKATAAQASAAAOAJQAOAJAHASIABAAIAAgvIAAgvIgBgnIAIACIAIAAIAHAAIAJgCIgCAhIgBAwIgBA2IAAAxIAAAtIABAqIgIgBIgGgBIgHABIgHABIABgjIgBAAQgDAHgIAKQgHAIgNAHQgMAGgQAAQgSABgRgKgAgbgOQgLAKgGAPQgFASAAAWQAAAcAIAQQAHARALAGQAMAHALgBQARAAAMgMQAMgMAGgSQAGgSgBgUQAAgigNgQQgNgSgaAAQgPAAgMAKg");
	this.shape_5.setTransform(41.3,66);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_6.setTransform(22.7,70.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgUBWIgHgBIgIABIgHABIABgiIAAgzIAAgLIAAggIgBgqIAHABIAIABIAHgBIAHgBIgBAVIgBAOIABAAQALgTAKgJQAMgKANAAIAFAAIAGACQgCAFAAAIIAAAQIgDACQgCgCgFgCQgFgCgFAAQgMABgIAGQgGAHgFAKQgEAMAAAOIAAAwIAAAdIABATIgHgBg");
	this.shape_7.setTransform(9.1,70.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAHCGIgHAAIgHAAIgIACIACgfIABglIAAgkIAAg/IAAgkIgBgmIgCgeIAIABIAHABIAHgBIAJgBIgCAeIgBAmIAAAkIAAA/IAAAkIABAlIACAfIgJgCg");
	this.shape_8.setTransform(492.9,21.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgjBOQgUgLgLgTQgLgTAAgYQAAgcAKgVQAJgVATgLQASgMAZAAQAZAAAQAKQARAKAIARQAIAQAAAUIAAAHIAAAHIgnAAIgngBIgVABIgYAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAOgHQAQgHAJgLIACABIgCARQgLAJgQAHQgRAGgRAAQgYAAgTgLgAgWhCQgLAKgFAOQgFAOgBAOIAXAAIAWABIAYgBIAYAAQAAgKgCgLQgCgLgEgJQgFgJgJgGQgJgGgNAAQgRAAgKAKg");
	this.shape_9.setTransform(479,26.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgbAxIAbhWQAAgEAEgFQADgEAIgBQAEABAFADQAEADAAAGIgCAIIgDAHIgrBKg");
	this.shape_10.setTransform(443.8,36.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgeBUQgPgEgNgLQgMgLgIgRQgIgRAAgYQAAgXAIgRQAIgRAMgLQANgKAPgFQAPgFAPAAQAQAAAPAFQAQAFAMAKQANALAIARQAHARAAAXQAAAYgHARQgIARgNALQgMALgQAEQgPAFgQAAQgPAAgPgFgAgfhBQgNALgFARQgGASABATQgBAUAGASQAFARANALQALALAUABQAVgBAMgLQAMgLAFgRQAGgSAAgUQAAgTgGgSQgFgRgMgLQgMgLgVAAQgUAAgLALg");
	this.shape_11.setTransform(429.9,26.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("ABzBWIgHgBIgIABIgIABIACglQACgdgBgtQABgTgJgMQgJgMgUAAQgNAAgKAEQgIAGgFAGIgFAIIgDAMIgBAWIAAAnIAAATIABASIABAUIgJgBIgGgBIgHABIgIABIADgpIAAgpIAAgYIAAgQIgCgJIgEgHQgFgHgHgFQgJgFgJABQgXAAgMAPQgLAPAAAcIAAAdIABAiIABAhIgIgBIgIgBIgIABIgHABIACghIAAgiIAAgjIAAgiIgCgiIAHABIAIABIAHgBIAIgBIgBAPIAAAOIABAAQAJgQANgIQAOgIARAAQANAAAKAEQALAFAGAIQAHAIAEAKIAAAAQAJgRAPgJQAPgJATAAQAQAAAMAFQANAGAHAMQAHANAAAUIgBATIgBAXIAAAkIAAATIABAUIgIgBg");
	this.shape_12.setTransform(405,26.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAIB9IgIgBIgGABIgIABIABghIABgiIAAgmIgBggIgBghIAIABIAGABIAIgBIAIgBQgCAQgBARIAAAgIAAAmIAAAiQABARACAQIgIgBgAgMheQgEgFgBgIQABgIAEgFQAGgFAGAAQAHAAAFAFQAFAFABAIQgBAIgFAFQgFAFgHABQgGgBgGgFg");
	this.shape_13.setTransform(384.9,22.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgNBkQgKgMgBgWIABgcIABglIABgtIgMAAIgMABIAAgFIABgDIgBgEIAAgEIAXABIAAgSIgBgWIAcgNIACAAIgCAbIgBAbIAPgBIAXgBIAAAEIAAAFIAAADIAAAEIgVgBIgRAAIgBAMIgBAYIgBAbIAAAbQAAANABANQACAMAGAIQAHAHANABIAIgBIAIgBIAAAIIgNAEQgHACgHgBQgVABgLgMg");
	this.shape_14.setTransform(375.2,24.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAHCGIgHAAIgHAAIgIACIACgfIABglIAAgkIAAg/IAAgkIgBgmIgCgeIAIABIAHABIAHgBIAJgBIgCAeIgBAmIAAAkIAAA/IAAAkIABAlIACAfIgJgCg");
	this.shape_15.setTransform(364.9,21.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag4B3QgPgQAAgcIABghIAAgbIAAgZIgBgeIAIABIAHABIAHgBIAIgBIgCAtIgBA1QgBATAEAKQADAKAFAFQAFAGAHADQAIAEAKABQAOgBAKgGQAKgHAFgJIAEgLIACgMIABgTIAAghIAAgdIAAgdIAHABIAHABIAIgBIAIgBIgDA0IAAA3IAAAhIABAeIgHgBIgHgBIgHABIgHABIABgQIAAgOIgBAAQgJAQgPAJQgPAJgPAAQgcAAgRgPgAgXhGIAzg2IAIgHQAEgCAEAAQAEAAAEADQAEADAAAFQAAAHgEAEIgJAHIgzAig");
	this.shape_16.setTransform(349.9,22.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgUBWIgHgBIgIABIgHABIABgiIAAgzIAAgLIAAggIgBgqIAHABIAIABIAHgBIAHgBIgBAVIgBAOIABABQALgUAKgJQAMgKANAAIAFAAIAGACQgCAFAAAIIAAAQIgDACQgCgCgFgCQgFgCgFAAQgMABgIAGQgGAHgFAKQgEAMAAAOIAAAwIAAAdIABATIgHgBg");
	this.shape_17.setTransform(315,26.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgdBUQgQgEgNgLQgNgLgHgRQgIgRAAgYQAAgXAIgRQAHgRANgLQANgKAQgFQAPgFAOAAQAPAAAQAFQAPAFANAKQAMALAJARQAHARAAAXQAAAYgHARQgJARgMALQgNALgPAEQgQAFgPAAQgOAAgPgFgAgghBQgMALgFARQgGASABATQgBAUAGASQAFARAMALQAMALAUABQAVgBAMgLQAMgLAGgRQAEgSAAgUQAAgTgEgSQgGgRgMgLQgMgLgVAAQgUAAgMALg");
	this.shape_18.setTransform(297.9,26.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag4CGIgJgBIgIABIgIABIACgeIABgmIAAgkIAAg4IAAglIgBglIgCgfIAIABIAIABIAJgBIAIgBIgCASIgBARIABAAQADgIAHgIQAIgJAMgHQAMgGAQgBQATAAARAKQAQAJALAUQAKATABAfQgBAfgLASQgLAUgSAKQgSAKgTAAQgSAAgOgJQgOgKgIgRIgBAAIAAAXIAAAkIABAmIACAeIgIgBgAAAh2QgRAAgMAKQgMAKgFARQgFASAAAUQAAAmANAQQAOATAYAAQARAAALgKQALgKAGgQQAFgRAAgWQAAgdgIgQQgHgQgLgGQgLgGgLAAIgCAAg");
	this.shape_19.setTransform(278.2,31.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgbAxIAbhWQAAgEAEgFQADgEAIgBQAEABAEADQAFADAAAGIgBAIIgFAHIgrBKg");
	this.shape_20.setTransform(241.8,36.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgmCEIgGgBIgHABIgGABQAPgYALgXIAXgvIgOghIgQgmIgRgqIgPgjIgKgXIAIABIAIABIAIgBIAJgBQAKAiAOAiIAbBEIAUgqIASgvIAQgvIAGABIAGABIAFgBIAGgBIgLAaIgVAsIgYA3IgZA3IgTAyIgOAjIgFgBg");
	this.shape_21.setTransform(232.2,31.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,520.1,91);


(lib.Símbolo5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgsDHQAYggANgfQAMgfAEgiQAFgiAAglQAAgkgFgiQgEgigMgfQgNgggYgfIAKgJQAlArAVA2QAVA1AAA5QAAAkgKAlQgIAlgTAjQgPAigbAdg");
	this.shape.setTransform(102.8,33.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("ACJCqIgNAAIgMAAIgMACIADhBIABhAIAAgrIg0gBIg0AAIgyAAIg1ABIAAArQAAAgABAgIADBBIgNgCIgLAAIgNAAIgMACIADhBIABhAIAAhVIgBhAIgDhBIAMACIANAAIALAAIANgCIgDBBQgBAgAAAgIAAASIA1ABIAyAAIA0AAIA0gBIAAgSIgBhAIgDhBIAMACIAMAAIANAAIAMgCIgCBBQgCAgAAAgIAABVQAAAgACAgIACBBIgMgCg");
	this.shape_1.setTransform(77,31);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AhgCdQgqgUgYgoQgXgogBg5QABg3AXgpQAYgnAqgWQAqgUA2AAQA3AAAqAUQAqAWAYAnQAXApABA3QgBA5gXAoQgYAogqAUQgqAWg3AAQg2AAgqgWgAhFiOQgfARgSAkQgSAjgBA2QABA3ASAjQASAkAfARQAfARAmAAQAnAAAfgRQAfgRASgkQASgjABg3QgBg2gSgjQgSgkgfgRQgfgRgnAAIgBAAQgmAAgeARg");
	this.shape_2.setTransform(36.7,31);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgYBvQgUg2AAg5QAAgjAJgmQAKgkARgjQAQgjAbgcIAKAJQgZAfgNAgQgLAfgEAiQgFAiAAAkQAAAlAFAiQAEAhALAgQANAfAZAgIgKAJQglgrgWg2g");
	this.shape_3.setTransform(9.6,33.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,112.6,63.5);


(lib.Símbolo4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABiB6IgIAAIgJAAIgJACIACgvIABgvIAAgeIgmgBIglAAIgkAAIgmABIAAAeIABAvIACAvIgJgCIgIAAIgJAAIgJACIACgvIABgvIAAg8IgBguIgCgvIAJABIAJABIAIgBIAJgBIgCAvIgBAuIAAANIAmABIAkAAIAlAAIAmgBIAAgNIgBguIgCgvIAJABIAJABIAIgBIAJgBIgCAvIgBAuIAAA8IABAvIACAvIgJgCg");
	this.shape.setTransform(186,67.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhFBxQgegPgRgdQgRgdgBgoQABgoARgcQARgdAegPQAegPAngBQAnABAeAPQAfAPARAdQARAcAAAoQAAAogRAdQgRAdgfAPQgeAQgnAAQgnAAgegQgAAyBnQAWgMAOgaQANgaAAgnQAAgmgNgaQgOgagWgMQgWgMgcAAQgbAAgWAMQgXAMgNAaQgNAaAAAmQAAAnANAaQANAaAXAMQAWAMAbAAQAcAAAWgMg");
	this.shape_1.setTransform(157,67.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgdBUQgQgEgMgLQgNgLgIgRQgHgRgBgYQABgXAHgRQAIgRANgLQAMgKAQgFQAOgFAPAAQAQAAAPAFQAQAFAMAKQAMALAIARQAIARAAAXQAAAYgIARQgIARgMALQgMALgQAEQgPAFgQAAQgPAAgOgFgAgfhBQgNALgFARQgFASAAATQAAAUAFASQAFARANALQAMALATABQAVgBAMgLQAMgLAFgRQAFgSABgUQgBgTgFgSQgFgRgMgLQgMgLgVAAQgTAAgMALg");
	this.shape_2.setTransform(112,71.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAHCGIgHAAIgHAAIgIACIACgfIABglIAAgkIAAg/IAAgkIgBgmIgCgeIAIABIAHABIAHgBIAJgBIgCAeIgBAmIAAAkIAAA/IAAAkIABAlIACAfIgJgCg");
	this.shape_3.setTransform(97,66.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAIB9IgIgBIgGABIgIABIABghIABgiIAAgmIgBggIgBghIAIABIAGABIAIgBIAIgBQgCAQgBARIAAAgIAAAmIAAAiQABARACAQIgIgBgAgMheQgEgFgBgIQABgIAEgFQAGgFAGAAQAHAAAFAFQAFAFABAIQgBAIgFAFQgFAFgHABQgGgBgGgFg");
	this.shape_4.setTransform(87,67.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUBWIgHAAIgIAAIgHACIABgjIAAg0IAAgJIAAghIgBgpIAHABIAIAAIAHAAIAHgBIgBAUIgBAOIABABQALgUAKgKQAMgJANgBIAFABIAGACQgCAEAAAJIAAAQIgDACQgCgDgFgBQgFgCgFAAQgMAAgIAHQgGAGgFALQgEAMAAAOIAAAvIAAAfIABATIgHgCg");
	this.shape_5.setTransform(77.1,71.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgrCBQgQgKgLgUQgKgTgBgfQABgfALgSQALgUASgKQASgKATAAQASAAAOAKQAOAIAHASIABAAIAAgwIAAgvIgBgmIAIABIAIABIAHgBIAJgBIgCAiIgBAwIgBA1IAAAyIAAAsIABAqIgIgCIgGAAIgHAAIgHACIABgkIgBAAQgDAJgIAIQgHAKgNAGQgMAGgQABQgSgBgRgIgAgbgOQgLAKgGAQQgFARAAAWQAAAdAIAPQAHARALAGQAMAGALAAQARAAAMgMQAMgMAGgRQAGgTgBgUQAAgigNgRQgNgSgaAAQgPAAgMALg");
	this.shape_6.setTransform(59.7,66.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAIB9IgIgBIgHABIgIABIACghIABgiIAAgmIgBggIgCghIAIABIAHABIAIgBIAIgBQgCAQAAARIgBAgIAAAmIABAiQAAARACAQIgIgBgAgLheQgGgFAAgIQAAgIAGgFQAEgFAHAAQAIAAAEAFQAGAFAAAIQAAAIgGAFQgEAFgIABQgHgBgEgFg");
	this.shape_7.setTransform(45,67.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("ABHBUIgJAAIgJAAIgJACIgYglIgYglIgaAlIgaAlIgGgCIgFAAIgHAAIgGACIAigrIAhgqIghgpIghgsIAKABIAJAAIAKAAIAJgBIAWAhIAWAhIAZghIAYghIAGABIAHAAIAGAAIAGgBIgiAmIggAnIAhAtIAkAwIgJgCg");
	this.shape_8.setTransform(31,71.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgdBUQgQgEgMgLQgNgLgIgRQgIgRAAgYQAAgXAIgRQAIgRANgLQAMgKAQgFQAOgFAPAAQAQAAAPAFQAQAFAMAKQANALAHARQAIARAAAXQAAAYgIARQgHARgNALQgMALgQAEQgPAFgQAAQgPAAgOgFgAgfhBQgNALgFARQgFASAAATQAAAUAFASQAFARANALQAMALATABQAVgBAMgLQAMgLAGgRQAEgSABgUQgBgTgEgSQgGgRgMgLQgMgLgVAAQgTAAgMALg");
	this.shape_9.setTransform(12,71.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAHCGIgHAAIgHAAIgIACIACgfIABglIAAgkIAAg/IAAgkIgBgmIgCgeIAIABIAHABIAHgBIAJgBIgCAeIgBAmIAAAkIAAA/IAAAkIABAlIACAfIgJgCg");
	this.shape_10.setTransform(492.3,21.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_11.setTransform(478.4,26.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgRBUQgPgFgOgLQgMgKgHgRQgIgRgBgYQABgeANgTQANgUAVgKQAVgJAVAAQAVAAAPAFQAPAEAIAHIgFALIgDAMIgDAAQgEgGgHgGQgGgHgJgEQgJgEgMAAQgTAAgNAKQgPAKgGARQgFASAAAVQAAAkAPATQARATAcAAQAPAAAOgHQAPgIAKgKIACABIgCAIIAAAJQgMAJgQAHQgQAGgRAAQgOAAgPgFg");
	this.shape_12.setTransform(460.3,26.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAIB9IgIgBIgGABIgJABIACghIABgiIAAgmIgBggIgCghIAJABIAGABIAIgBIAIgBQgCAQgBARIAAAgIAAAmIAAAiQABARACAQIgIgBgAgMheQgFgFAAgIQAAgIAFgFQAFgFAHAAQAHAAAFAFQAGAFAAAIQAAAIgGAFQgFAFgHABQgHgBgFgFg");
	this.shape_13.setTransform(446.3,22.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgrCAQgQgJgLgTQgKgUgBgfQABgeALgTQALgUASgKQASgKATAAQASAAAOAJQAOAJAHASIABAAIAAgvIAAgvIgBgnIAIACIAIAAIAHAAIAJgCIgCAhIgBAwIgBA2IAAAxIAAAtIABAqIgIgBIgGgBIgHABIgHABIABgjIgBAAQgDAHgIAKQgHAIgNAHQgMAGgQAAQgSABgRgKgAgbgOQgLAKgGAPQgFASAAAWQAAAcAIAQQAHARALAGQAMAHALgBQARAAAMgMQAMgMAGgSQAGgSgBgUQAAgigNgQQgNgSgaAAQgPAAgMAKg");
	this.shape_14.setTransform(431,21.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_15.setTransform(412.4,26.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgUBWIgHgBIgIABIgHABIABgiIAAgzIAAgLIAAggIgBgqIAHABIAIABIAHgBIAHgBIgBAVIgBAOIABABQALgUAKgJQAMgKANAAIAFAAIAGACQgCAFAAAIIAAAQIgDACQgCgCgFgCQgFgCgFAAQgMABgIAGQgGAHgFAKQgEAMAAAOIAAAwIAAAdIABATIgHgBg");
	this.shape_16.setTransform(398.9,26.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("ABABWIgIgBIgHABIgIABIACgnIABgpIAAgUQAAgbgLgOQgKgOgSABQgXAAgMAPQgMAPAAAcIAAAdIABAiQAAARACAQIgIgBIgIgBIgIABIgIABIACghIAAgiIAAgjIAAgiIgCgiIAIABIAIABIAGgBIAIgBIgBAPIAAAOIABAAQAKgPAOgJQAOgIARAAQAOgBANAGQANAFAJAOQAJANAAAZIgBAeIAAAjIAAAXIAAAXIgHgBg");
	this.shape_17.setTransform(361.8,26.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag3BIQgQgQgBgcIABgeIABgbIgBgcIAAgdIAIABIAHAAIAIAAIAHgBIgDAvIgBAzQABASADAKQADAKAEAFQAGAGAIAEQAHADALABQANgBAKgGQAKgGAEgKIAFgLIACgMIABgTIAAgfIAAgfIgBgcIAIABIAIAAIAIAAIAGgBIgCA2IAAA1IAAAgIABAfIgHgCIgHAAIgHAAIgHACIABgQIAAgPIgBAAQgJAQgPAJQgOAJgQAAQgdAAgPgPg");
	this.shape_18.setTransform(341.8,26.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgkBVQgLgDgHgFIAEgMIADgOIAEAAQADAFAFAGQAGAGAJAEQAHAEALAAQAHAAAIgEQAIgEAFgHQAEgHABgLQAAgNgJgGQgJgHgMgDIgYgIQgMgFgJgHQgIgKgBgSQAAgQAIgMQAGgMAOgHQANgHASAAQANAAAJAEIARAGIgDAJIgEAJIgBAIIgEAAQgDgJgIgHQgJgGgMgBQgGAAgGADQgIAEgEAGQgEAHgBAKQABAOAIAHQAJAGAKAEIAaAIQAMAEAIAHQAJAJAAASQAAAOgIANQgHANgPAJQgOAIgTAAQgQAAgMgEg");
	this.shape_19.setTransform(304.8,26.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgjB6QgUgKgLgTQgKgTgBgZQAAgdAKgUQAKgUASgMQASgLAZAAQAYAAASAKQAQAKAIARQAIAOAAAUIAAAHIgBAHIgmgBIgmAAIgWAAIgYABIAAAGIAAAEQAAATAHAPQAHAPAOAJQAOAIASABQAPAAAOgIQAQgGAJgMIACABIgCASQgMAJgQAHQgPAFgSABQgXAAgUgMgAgWgWQgLALgFAMQgGAOAAAOIAXAAIAWAAIAYAAIAYAAQAAgKgCgLQgCgJgFgKQgEgIgJgGQgJgHgNAAQgQAAgLAKgAgShGIAzg2IAHgHQAFgCAEAAQAEAAAEADQAEADAAAFQAAAHgEAEQgFAEgEADIgzAig");
	this.shape_20.setTransform(288.9,22.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("Ag3BIQgQgQgBgcIABgeIABgbIgBgcIAAgdIAIABIAHAAIAIAAIAHgBIgDAvIgBAzQABASADAKQADAKAEAFQAGAGAIAEQAHADALABQANgBAKgGQAKgGAEgKIAFgLIACgMIABgTIAAgfIAAgfIgBgcIAIABIAIAAIAIAAIAGgBIgCA2IAAA1IAAAgIABAfIgHgCIgHAAIgHAAIgHACIABgQIAAgPIgBAAQgJAQgPAJQgOAJgQAAQgdAAgPgPg");
	this.shape_21.setTransform(269.8,26.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("Ag4CGIgJgBIgIABIgIABIACgeIABgmIAAgkIAAg4IAAglIgBglIgCgfIAIABIAIABIAJgBIAIgBIgCASIgBARIABAAQADgIAHgIQAIgJAMgHQAMgGAQgBQATAAARAKQAQAJALAUQAKATABAfQgBAfgLASQgLAUgSAKQgSAKgTAAQgSAAgOgJQgOgKgIgRIgBAAIAAAXIAAAkIABAmIACAeIgIgBgAAAh2QgRAAgMAKQgMAKgFARQgFASAAAUQAAAmANAQQAOATAYAAQARAAALgKQALgKAGgQQAFgRAAgWQAAgdgIgQQgHgQgLgGQgLgGgLAAIgCAAg");
	this.shape_22.setTransform(250,31.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgjBVQgMgDgHgFIAEgMIADgOIAEAAQADAFAFAGQAGAGAJAEQAHAEALAAQAHAAAIgEQAIgEAEgHQAFgHABgLQAAgNgJgGQgJgHgMgDIgYgIQgMgFgJgHQgIgKgBgSQAAgQAIgMQAGgMAOgHQANgHASAAQANAAAJAEIARAGIgDAJIgEAJIgBAIIgEAAQgDgJgIgHQgJgGgMgBQgGAAgGADQgIAEgEAGQgEAHgBAKQABAOAIAHQAJAGAKAEIAZAIQANAEAIAHQAJAJAAASQAAAOgIANQgHANgPAJQgOAIgTAAQgQAAgLgEg");
	this.shape_23.setTransform(232.8,26.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgjBOQgUgLgLgTQgKgTgBgYQAAgcAKgVQAKgVASgLQASgMAZAAQAYAAASAKQAQAKAIARQAIAQAAAUIAAAHIgBAHIgmAAIgmgBIgWABIgYAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAOgHQAQgHAJgLIACABIgCARQgMAJgQAHQgPAGgSAAQgXAAgUgLgAgWhCQgLAKgFAOQgGAOAAAOIAXAAIAWABIAYgBIAYAAQAAgKgCgLQgCgLgFgJQgEgJgJgGQgJgGgOAAQgPAAgLAKg");
	this.shape_24.setTransform(216.9,26.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgrCAQgQgJgLgTQgKgUgBgfQABgeALgTQALgUASgKQASgKATAAQASAAAOAJQAOAJAHASIABAAIAAgvIAAgvIgBgnIAIACIAIAAIAHAAIAJgCIgCAhIgBAwIgBA2IAAAxIAAAtIABAqIgIgBIgGgBIgHABIgHABIABgjIgBAAQgDAHgIAKQgHAIgNAHQgMAGgQAAQgSABgRgKgAgbgOQgLAKgGAPQgFASAAAWQAAAcAIAQQAHARALAGQAMAHALgBQARAAAMgMQAMgMAGgSQAGgSgBgUQAAgigNgQQgNgSgaAAQgPAAgMAKg");
	this.shape_25.setTransform(197.5,21.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,499.5,91.9);


(lib.Símbolo3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AC6CtIgMAAIgLAAIgMACIgLiCIgOh+IgBAAQgiA+ghA+QgiA/gcBDIgEAAQgeg/ghhAIhCh/IgBAAIgIBDIgHBGIgGBDQgDAfAAAVIgIgCIgJAAIgJAAIgJACIASh1IARh3QAIg8AGg1IAIAAQAiBGAkBEIBICHIASgjIAcg0IAig9IAkhBIAgg8IAHAAIANB6IANByIAPBxIgMgCg");
	this.shape.setTransform(24.2,30.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.7,63.5);


(lib.Símbolo2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgbAxIAbhWQAAgEAEgFQADgEAIgBQAEABAEADQAFADAAAGIgBAIIgFAHIgrBKg");
	this.shape.setTransform(159.9,36.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAHCGIgHAAIgHAAIgIACIACgfIABglIAAgkIAAg/IAAgkIgBgmIgCgeIAIABIAHABIAHgBIAJgBIgCAeIgBAmIAAAkIAAA/IAAAkIABAlIACAfIgJgCg");
	this.shape_1.setTransform(151,21.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_2.setTransform(137.1,26.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgNBkQgKgMgBgWIABgcIABglIACgtIgNAAIgMABIAAgFIABgDIgBgEIAAgEIAXABIAAgSIgBgWIAcgNIACAAIgCAbIgBAbIAOgBIAYgBIAAAEIAAAFIAAADIAAAEIgVgBIgRAAIgBAMIgBAYIgBAbIAAAbQAAANABANQACAMAGAIQAHAHANABIAIgBIAIgBIAAAIIgNAEQgHACgHgBQgVABgLgMg");
	this.shape_3.setTransform(123.3,24.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgjBOQgUgLgLgTQgLgTAAgYQAAgcAKgVQAJgVATgLQASgMAZAAQAZAAAQAKQARAKAIARQAIAQAAAUIAAAHIAAAHIgnAAIgngBIgVABIgYAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAOgHQAQgHAJgLIACABIgCARQgLAJgQAHQgRAGgRAAQgYAAgTgLgAgWhCQgLAKgFAOQgFAOgBAOIAXAAIAWABIAYgBIAYAAQAAgKgCgLQgCgLgEgJQgFgJgJgGQgJgGgNAAQgRAAgKAKg");
	this.shape_4.setTransform(109.1,26.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AB0BWIgIgBIgJABIgHABIACglQACgdAAgtQAAgTgJgMQgIgMgWAAQgNAAgIAEQgKAGgFAGIgEAIIgCAMIgCAWIAAAnIAAATIABASIABAUIgIgBIgHgBIgHABIgIABIACgpIACgpIgBgYIgBgQIgCgJIgDgHQgEgHgJgFQgIgFgJABQgYAAgKAPQgMAPAAAcIAAAdIAAAiIADAhIgIgBIgIgBIgJABIgIABIACghIABgiIAAgjIgBgiIgCgiIAIABIAJABIAGgBIAIgBIgBAPIAAAOIAAAAQAKgQANgIQAOgIARAAQAMAAAMAEQALAFAFAIQAHAIADAKIABAAQAJgRAPgJQAPgJAUAAQAPAAANAFQAMAGAHAMQAHANABAUIgBATIgBAXIgBAkIABATIAAAUIgHgBg");
	this.shape_5.setTransform(85.1,26.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABABWIgIgBIgHABIgIABIACgnIABgpIAAgUQAAgbgLgOQgKgOgSABQgXAAgMAPQgMAPAAAcIAAAdIABAiQAAARACAQIgIgBIgIgBIgIABIgIABIACghIAAgiIAAgjIAAgiIgCgiIAIABIAIABIAGgBIAIgBIgBAPIAAAOIABAAQAKgPAOgJQAOgIARAAQAOgBANAGQANAFAJAOQAJANAAAZIgBAeIAAAjIAAAXIAAAXIgHgBg");
	this.shape_6.setTransform(40,26.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhQBlQgZgZABg1IAAgcIABgbIAAg2IgCgnIAJABIAKABIAIgBIAHgBIgCAeIgBArIgBAyQAAARABAUQACAUAHAQQAHARARALQARAKAbAAQAeAAAQgMQAQgMAHgTQAHgSACgUIABgkIAAhPQAAgcgCgKIAHABIAIABIAFgBIAGgBQgCARgBAZIgDA0IgBA1QgBAhgLAWQgNAXgWANQgXANgeAAQg2AAgZgZg");
	this.shape_7.setTransform(16,23.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,168.2,46.9);


(lib.Símbolo1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNBPQgGgFAAgIQAAgJAGgGQAGgGAHAAQAIAAAGAGQAGAGAAAJQAAAIgGAFQgGAHgIAAQgHAAgGgHgAgNgyQgGgGAAgIQAAgJAGgGQAGgFAHgBQAIABAGAFQAGAGAAAJQAAAIgGAGQgGAGgIAAQgHAAgGgGg");
	this.shape.setTransform(158.6,71.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_1.setTransform(144.7,71.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUBWIgHgBIgIABIgHACIABgjIAAg0IAAgJIAAghIgBgqIAHACIAIAAIAHAAIAHgCIgBAVIgBAOIABAAQALgTAKgKQAMgKANAAIAFABIAGACQgCAFAAAIIAAAQIgDACQgCgCgFgCQgFgCgFAAQgMABgIAGQgGAHgFALQgEALAAAOIAAAvIAAAeIABAUIgHgCg");
	this.shape_2.setTransform(131.1,71.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag4BIQgPgQAAgcIABgeIAAgbIAAgcIgBgdIAIABIAHAAIAHAAIAIgBIgCAvIgBAzQAAASADAKQADAKAFAFQAFAGAHAEQAIADAKABQAOgBAKgGQAKgGAFgKIAEgLIACgMIABgTIAAgfIAAgfIgBgcIAIABIAHAAIAIAAIAIgBIgDA2IAAA1IAAAgIABAfIgHgCIgHAAIgHAAIgHACIABgQIAAgPIgBAAQgJAQgPAJQgPAJgPAAQgcAAgRgPg");
	this.shape_3.setTransform(114,71.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgMBjQgLgMAAgVIAAgdIACgkIABgtIgMAAIgOABIABgEIAAgFIAAgDIgBgEIAZABIgBgSIgBgWIAcgMIABAAIgBAaIgBAbIAOgBIAYgBIAAAFIAAADIAAAEIAAAEIgUgBIgSAAIgBALIgBAZIAAAaIAAAbQgBAOACANQABAMAHAIQAGAHAOABIAIgBIAIgBIAAAIIgOAEIgOABQgVAAgKgMg");
	this.shape_4.setTransform(99.3,69.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgRBUQgPgFgOgLQgMgKgIgRQgHgRgBgYQABgeANgTQANgUAVgKQAVgJAVAAQAVAAAPAFQAPAEAIAHIgFALIgDAMIgDAAQgEgGgHgGQgGgHgJgEQgJgEgMAAQgTAAgNAKQgOAKgHARQgFASAAAVQAAAkAPATQARATAcAAQAPAAAOgHQAPgIAKgKIACABIgCAIIAAAJQgMAJgQAHQgQAGgRAAQgOAAgPgFg");
	this.shape_5.setTransform(85,71.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag4BIQgPgQgBgcIABgeIABgbIgBgcIAAgdIAIABIAHAAIAIAAIAHgBIgDAvIgBAzQABASADAKQADAKAEAFQAFAGAJAEQAHADALABQANgBAKgGQAKgGAEgKIAFgLIACgMIABgTIAAgfIAAgfIgBgcIAIABIAIAAIAIAAIAGgBIgCA2IAAA1IAAAgIABAfIgHgCIgHAAIgHAAIgHACIABgQIAAgPIgBAAQgJAQgPAJQgOAJgQAAQgdAAgQgPg");
	this.shape_6.setTransform(66,71.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgUBWIgHgBIgIABIgHACIABgjIAAg0IAAgJIAAghIgBgqIAHACIAIAAIAHAAIAHgCIgBAVIgBAOIABAAQALgTAKgKQAMgKANAAIAFABIAGACQgCAFAAAIIAAAQIgDACQgCgCgFgCQgFgCgFAAQgMABgIAGQgGAHgFALQgEALAAAOIAAAvIAAAeIABAUIgHgCg");
	this.shape_7.setTransform(51.1,71.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgNBjQgLgMABgVIAAgdIABgkIABgtIgLAAIgOABIABgEIABgFIgBgDIgBgEIAYABIAAgSIgBgWIAcgMIABAAIgBAaIgBAbIAPgBIAXgBIgBAFIAAADIAAAEIABAEIgVgBIgRAAIgBALIgBAZIAAAaIAAAbQgBAOABANQACAMAHAIQAFAHAOABIAJgBIAIgBIAAAIIgOAEIgOABQgUAAgMgMg");
	this.shape_8.setTransform(39.3,69.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgjBVQgLgDgIgFIAEgMIADgOIAEAAQADAFAFAGQAGAGAJAEQAHAEALAAQAHAAAIgEQAIgEAFgHQAEgHABgLQAAgNgJgGQgJgHgMgDIgYgIQgMgFgJgHQgIgKAAgSQgBgQAIgMQAGgMAOgHQANgHASAAQANAAAJAEIARAGIgDAJIgEAJIgBAIIgEAAQgEgJgIgHQgIgGgMgBQgGAAgGADQgIAEgEAGQgFAHAAAKQABAOAIAHQAJAGAKAEIAaAIQAMAEAIAHQAJAJAAASQAAAOgIANQgHANgPAJQgPAIgRAAQgRAAgLgEg");
	this.shape_9.setTransform(27,71.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgjBOQgUgLgLgTQgKgTgBgYQAAgcAKgVQAJgVATgLQASgMAZAAQAZAAAQAKQARAKAIARQAIAQAAAUIAAAHIgBAHIgmAAIgngBIgVABIgYAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAOgHQAPgHAKgLIACABIgCARQgMAJgPAHQgQAGgSAAQgYAAgTgLgAgWhCQgLAKgFAOQgFAOgBAOIAXAAIAWABIAYgBIAYAAQAAgKgCgLQgCgLgEgJQgFgJgJgGQgJgGgNAAQgQAAgLAKg");
	this.shape_10.setTransform(11.1,71.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_11.setTransform(489.1,26.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAHCGIgHAAIgHAAIgIACIACgfIABglIAAgkIAAg/IAAgkIgBgmIgCgeIAIABIAHABIAHgBIAJgBIgCAeIgBAmIAAAkIAAA/IAAAkIABAlIACAfIgJgCg");
	this.shape_12.setTransform(475,21.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_13.setTransform(439.5,26.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgUBWIgHgBIgIABIgHABIABgiIAAgzIAAgLIAAggIgBgqIAHABIAIABIAHgBIAHgBIgBAVIgBAOIABABQALgUAKgJQAMgKANAAIAFAAIAGACQgCAFAAAIIAAAQIgDACQgCgCgFgCQgFgCgFAAQgMABgIAGQgGAHgFAKQgEAMAAAOIAAAwIAAAdIABATIgHgBg");
	this.shape_14.setTransform(425.9,26.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgMBkQgMgMAAgWIABgcIACglIABgtIgNAAIgMABIAAgFIAAgDIAAgEIAAgEIAYABIgBgSIgBgWIAcgNIACAAIgCAbIgBAbIAOgBIAYgBIAAAEIAAAFIAAADIAAAEIgUgBIgSAAIgBAMIgBAYIgBAbIAAAbQAAANABANQACAMAGAIQAHAHAOABIAHgBIAIgBIAAAIIgNAEQgHACgHgBQgVABgKgMg");
	this.shape_15.setTransform(414.1,24.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgkBVQgKgDgIgFIAFgMIACgOIAEAAQACAFAGAGQAGAGAJAEQAIAEAKAAQAHAAAIgEQAIgEAEgHQAGgHAAgLQgBgNgIgGQgIgHgNgDIgXgIQgNgFgJgHQgIgKgBgSQABgQAGgMQAIgMANgHQAOgHAQAAQANAAAKAEIASAGIgFAJIgCAJIgCAIIgFAAQgDgJgHgHQgJgGgMgBQgFAAgIADQgGAEgFAGQgEAHgBAKQABAOAIAHQAIAGALAEIAZAIQANAEAJAHQAIAJAAASQAAAOgHANQgJANgOAJQgOAIgTAAQgQAAgMgEg");
	this.shape_16.setTransform(401.8,26.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgjBOQgTgLgMgTQgKgTgBgYQAAgcAKgVQAJgVASgLQATgMAYAAQAaAAARAKQAQAKAIARQAIAQAAAUIAAAHIgBAHIgmAAIgmgBIgXABIgXAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAPgHQAOgHAKgLIACABIgCARQgLAJgRAHQgQAGgQAAQgYAAgUgLgAgWhCQgLAKgFAOQgGAOAAAOIAXAAIAWABIAYgBIAXAAQABgKgCgLQgCgLgFgJQgEgJgJgGQgJgGgOAAQgQAAgKAKg");
	this.shape_17.setTransform(385.9,26.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag4BIQgPgQgBgcIACgeIAAgbIAAgcIgBgdIAIABIAHAAIAHAAIAIgBIgCAvIgCAzQAAASAEAKQADAKAFAFQAFAGAHAEQAIADAKABQAOgBAKgGQAKgGAFgKIAEgLIACgMIABgTIAAgfIAAgfIgBgcIAIABIAIAAIAIAAIAHgBIgDA2IAAA1IAAAgIABAfIgHgCIgHAAIgHAAIgHACIABgQIAAgPIgBAAQgJAQgPAJQgPAJgPAAQgdAAgQgPg");
	this.shape_18.setTransform(366.8,26.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("ABzBWIgHgBIgJABIgHABIACglQABgdAAgtQABgTgJgMQgJgMgUAAQgNAAgKAEQgIAGgFAGIgFAIIgCAMIgCAWIAAAnIAAATIABASIABAUIgJgBIgGgBIgHABIgIABIADgpIABgpIgBgYIAAgQIgCgJIgEgHQgFgHgHgFQgJgFgJABQgXAAgMAPQgLAPAAAcIAAAdIABAiIABAhIgIgBIgIgBIgIABIgIABIADghIAAgiIAAgjIAAgiIgDgiIAIABIAIABIAHgBIAIgBIgBAPIAAAOIABAAQAJgQANgIQAOgIARAAQAMAAALAEQALAFAGAIQAHAIAEAKIAAAAQAJgRAPgJQAPgJATAAQAQAAAMAFQANAGAHAMQAHANAAAUIgBATIgBAXIAAAkIAAATIABAUIgIgBg");
	this.shape_19.setTransform(341.9,26.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgjBOQgUgLgLgTQgLgTAAgYQAAgcAKgVQAJgVATgLQASgMAZAAQAZAAAQAKQARAKAIARQAIAQAAAUIAAAHIAAAHIgnAAIgngBIgVABIgYAAIAAAEIAAAEQAAATAHAPQAHAPAOAJQAOAJASAAQAPAAAOgHQAQgHAJgLIACABIgCARQgLAJgQAHQgRAGgRAAQgYAAgTgLgAgWhCQgLAKgFAOQgFAOgBAOIAXAAIAWABIAYgBIAYAAQAAgKgCgLQgCgLgEgJQgFgJgJgGQgJgGgNAAQgRAAgKAKg");
	this.shape_20.setTransform(296.3,26.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgkBVQgLgDgHgFIAFgMIACgOIAEAAQADAFAFAGQAGAGAJAEQAHAEALAAQAHAAAIgEQAIgEAEgHQAGgHAAgLQgBgNgIgGQgIgHgNgDIgXgIQgNgFgJgHQgIgKgBgSQABgQAGgMQAIgMANgHQAOgHAQAAQANAAAKAEIARAGIgEAJIgCAJIgCAIIgEAAQgEgJgHgHQgJgGgMgBQgGAAgGADQgIAEgEAGQgEAHgBAKQABAOAIAHQAIAGALAEIAZAIQANAEAJAHQAIAJAAASQAAAOgHANQgJANgOAJQgOAIgTAAQgQAAgMgEg");
	this.shape_21.setTransform(280.2,26.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("ABABWIgIgBIgHABIgIABIACgnIABgpIAAgUQAAgbgLgOQgKgOgSABQgXAAgMAPQgMAPAAAcIAAAdIABAiQAAARACAQIgIgBIgIgBIgIABIgIABIACghIAAgiIAAgjIAAgiIgCgiIAIABIAIABIAGgBIAIgBIgBAPIAAAOIABAAQAKgPAOgJQAOgIARAAQAOgBANAGQANAFAJAOQAJANAAAZIgBAeIAAAjIAAAXIAAAXIgHgBg");
	this.shape_22.setTransform(241.6,26.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgdCBQgQgFgMgLQgOgKgHgRQgIgSAAgXQAAgZAIgRQAHgPAOgLQAMgKAQgGQAPgEAOAAQAPAAAQAEQAPAGANAKQANALAHAPQAIARAAAZQAAAXgIASQgHARgNAKQgNALgPAFQgQAFgPAAQgOAAgPgFgAgfgVQgNAMgFAPQgFASAAAVQAAAUAFASQAFARANALQALALAUAAQAVAAAMgLQAMgLAGgRQAEgSAAgUQAAgVgEgSQgGgPgMgMQgMgLgVAAQgUAAgLALgAgXhGIAzg2IAIgHQAEgCAEAAQAEAAAEADQAEADAAAFQAAAHgEAEQgEAEgFADIgzAig");
	this.shape_23.setTransform(221.6,22.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAHB9IgHgBIgGABIgIABIABghIABgiIAAgmIgBggIgBghIAIABIAGABIAHgBIAJgBQgCAQgBARIAAAgIAAAmIAAAiQABARACAQIgJgBgAgMheQgEgFgBgIQABgIAEgFQAFgFAHAAQAIAAAEAFQAFAFABAIQgBAIgFAFQgEAFgIABQgHgBgFgFg");
	this.shape_24.setTransform(206.6,22.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgRBUQgPgFgNgLQgNgKgHgRQgIgRAAgYQAAgeANgTQAOgUAUgKQAVgJAWAAQATAAAQAFQAPAEAHAHIgEALIgEAMIgDAAQgDgGgGgGQgHgHgJgEQgJgEgMAAQgTAAgOAKQgOAKgFARQgHASAAAVQABAkAPATQAQATAcAAQAPAAAPgHQAPgIAJgKIACABIgBAIIgBAJQgLAJgQAHQgQAGgRAAQgOAAgPgFg");
	this.shape_25.setTransform(192.6,26.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgyBUQgLgGgHgJQgGgKgBgOQABgWANgMQANgLAYgCIAdgGQALgCAFgDQAFgCABgEIABgJQAAgMgEgKQgEgKgIgHQgJgGgMAAQgPAAgMAGQgMAHgHALIgEAAIAAgSQAQgMAOgFQAOgEAOAAQAZAAAPAOQAQAPABAYIgBAnIgBArIABAMQAAAGADAEQADAEAHABIAEgBIAEgBIAAAIIgKADIgNACQgMAAgGgGQgGgHgBgJQgNANgNAHQgLAGgSAAQgMAAgLgFgAAGAAIgXAGQgMAEgIAHQgIAIAAAPQAAALAEAIQAFAIAHADQAHAEAIAAQAOAAAJgHQALgIAHgKIABg0QgJADgNAAg");
	this.shape_26.setTransform(174.7,26.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("Ag3BIQgQgQAAgcIABgeIAAgbIAAgcIgBgdIAIABIAHAAIAHAAIAIgBIgCAvIgBAzQgBASAEAKQADAKAEAFQAFAGAIAEQAIADAKABQAOgBAKgGQAKgGAFgKIAEgLIACgMIABgTIAAgfIAAgfIAAgcIAHABIAHAAIAIAAIAHgBIgCA2IAAA1IAAAgIABAfIgHgCIgHAAIgHAAIgHACIABgQIAAgPIgBAAQgJAQgPAJQgPAJgPAAQgcAAgQgPg");
	this.shape_27.setTransform(155.6,26.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("ABABWIgIgBIgHABIgIABIACgnIABgpIAAgUQAAgbgLgOQgKgOgSABQgXAAgMAPQgMAPAAAcIAAAdIABAiQAAARACAQIgIgBIgIgBIgIABIgIABIACghIAAgiIAAgjIAAgiIgCgiIAIABIAIABIAGgBIAIgBIgBAPIAAAOIABAAQAKgPAOgJQAOgIARAAQAOgBANAGQANAFAJAOQAJANAAAZIgBAeIAAAjIAAAXIAAAXIgHgBg");
	this.shape_28.setTransform(135.6,26.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAIB9IgIgBIgHABIgIABIACghIABgiIAAgmIgBggIgCghIAIABIAHABIAIgBIAIgBQgCAQAAARIgBAgIAAAmIABAiQAAARACAQIgIgBgAgLheQgGgFAAgIQAAgIAGgFQAEgFAHAAQAIAAAEAFQAGAFAAAIQAAAIgGAFQgEAFgIABQgHgBgEgFg");
	this.shape_29.setTransform(120.6,22.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgMBkQgMgMAAgWIABgcIACglIABgtIgNAAIgNABIABgFIAAgDIAAgEIgBgEIAZABIgBgSIgBgWIAcgNIABAAIgBAbIgBAbIAOgBIAYgBIAAAEIAAAFIAAADIAAAEIgUgBIgSAAIgBAMIgBAYIgBAbIAAAbQAAANACANQABAMAGAIQAHAHAOABIAIgBIAHgBIAAAIIgNAEQgHACgHgBQgVABgKgMg");
	this.shape_30.setTransform(110.9,24.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("ABABWIgIgBIgHABIgIABIACgnIABgpIAAgUQAAgbgLgOQgKgOgSABQgXAAgMAPQgMAPAAAcIAAAdIABAiQAAARACAQIgIgBIgIgBIgIABIgIABIACghIAAgiIAAgjIAAgiIgCgiIAIABIAIABIAGgBIAIgBIgBAPIAAAOIABAAQAKgPAOgJQAOgIARAAQAOgBANAGQANAFAJAOQAJANAAAZIgBAeIAAAjIAAAXIAAAXIgHgBg");
	this.shape_31.setTransform(95.6,26.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgdBUQgQgEgNgLQgNgLgHgRQgIgRAAgYQAAgXAIgRQAHgRANgLQANgKAQgFQAPgFAOAAQAPAAAQAFQAPAFANAKQAMALAJARQAHARAAAXQAAAYgHARQgJARgMALQgNALgPAEQgQAFgPAAQgOAAgPgFgAgghBQgMALgFARQgGASABATQgBAUAGASQAFARAMALQAMALAUABQAVgBAMgLQAMgLAGgRQAEgSAAgUQAAgTgEgSQgGgRgMgLQgMgLgVAAQgUAAgMALg");
	this.shape_32.setTransform(75.6,26.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgRBUQgPgFgNgLQgNgKgIgRQgHgRAAgYQAAgeANgTQAOgUAUgKQAVgJAWAAQATAAAQAFQAQAEAGAHIgEALIgEAMIgCAAQgEgGgGgGQgHgHgJgEQgJgEgLAAQgUAAgOAKQgOAKgFARQgHASAAAVQABAkAQATQAQATAcAAQAPAAAOgHQAPgIAKgKIABABIgBAIIAAAJQgMAJgQAHQgQAGgRAAQgOAAgPgFg");
	this.shape_33.setTransform(56.6,26.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("ABoB9IgKgBIgJABIgJABQgEgNgGgQIgOgiIgOghIgXgBIgWAAIgWAAIgWABIgVA1QgJAagEARIgIgBIgGgBIgGABIgHABIA4h+IA4h9IAFAAIAXA3IAZA7IAYA3IAVAxIAPAhIgJgBgAgsANIAUAAIATABIASAAIAUgBIgmhZg");
	this.shape_34.setTransform(14,22.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,500,91.7);


(lib.Symbol26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCFF00").s().p("AmEGEQihihAAjjQAAjiChihQChihDjAAQDjAAChChQChChAADiQAADjihChQihChjjAAQjjAAihihg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(10).to({_off:true},1).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55,-55,110,110);


(lib.CopiadeSímbolo1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.instance = new lib.flechas1();
	this.instance.setTransform(0,0,1.481,1.481);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,80,80);


// stage content:
(lib.Pag97 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_9 = function() {
		root= this;
		root.stop();
		var frame=10;
		setTimeout(function(){
			if(frame==10){
				frame=11;
		  root.gotoAndPlay(10);	
		  }
			},2000);
		
		root.sig1.addEventListener("click",fsig1);
			function fsig1(event){
				frame=29;
				 root.gotoAndPlay(28);
				 
				}
	}
	this.frame_27 = function() {
		root.stop();
		frame=28;
		setTimeout(
		function(){
			 if(frame==28){
		        root.luz1.visible=true;		 
				 }
			},2000);
	}
	this.frame_28 = function() {
		root.sig2.addEventListener("click",function(){
				frame=41;
				root.gotoAndPlay(40);
				});
	}
	this.frame_38 = function() {
		root.stop();
		frame=39;
		 setTimeout(
		 function(){
		  	  if(frame==39){
		    root.luz2.visible=true;		  
				  }
			 },3000);
	}
	this.frame_49 = function() {
		root.stop();
		setTimeout(function(){
		  root.gotoAndPlay(50);	
			},3500);
	}
	this.frame_60 = function() {
		root.stop();
		
		setTimeout(function(){
		  root.gootAndPaly(61);
			},4000);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(9).call(this.frame_9).wait(18).call(this.frame_27).wait(1).call(this.frame_28).wait(10).call(this.frame_38).wait(11).call(this.frame_49).wait(11).call(this.frame_60).wait(40));

	// Capa 14
	this.instance = new lib.Símbolo8();
	this.instance.setTransform(825.4,502.6,1,1,0,0,0,255.8,44.9);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(64).to({_off:false},0).wait(36));

	// Capa 13
	this.instance_1 = new lib.Símbolo7();
	this.instance_1.setTransform(826.7,437.1,1,1,0,0,0,257.1,69.1);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(49).to({_off:false},0).to({_off:true},36).wait(15));

	// Capa 10
	this.instance_2 = new lib.Símbolo6();
	this.instance_2.setTransform(829.7,368.8,1,1,0,0,0,260.1,45.5);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(39).to({_off:false},0).to({alpha:1},10).to({_off:true},36).wait(15));

	// Capa 9
	this.instance_3 = new lib.Símbolo5();
	this.instance_3.setTransform(155.2,164.3,1,1,0,0,0,56.3,31.8);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(28).to({_off:false},0).to({alpha:1},10).to({_off:true},47).wait(15));

	// Capa 8
	this.instance_4 = new lib.Símbolo4();
	this.instance_4.setTransform(818.7,324,1,1,0,0,0,249.8,46);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(28).to({_off:false},0).to({alpha:1},10).to({_off:true},47).wait(15));

	// Capa 7
	this.instance_5 = new lib.Símbolo3();
	this.instance_5.setTransform(67.4,167.9,1,1,0,0,0,24.3,31.8);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(19).to({_off:false},0).to({alpha:1},8).to({_off:true},58).wait(15));

	// Capa 5
	this.instance_6 = new lib.Símbolo2();
	this.instance_6.setTransform(642.9,301.4,1,1,0,0,0,74.1,23.4);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(10).to({_off:false},0).to({alpha:1},9).to({_off:true},66).wait(15));

	// Capa 3
	this.instance_7 = new lib.Símbolo1();
	this.instance_7.setTransform(817.1,224.3,1,1,0,0,0,250,45.9);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({alpha:1},9).to({_off:true},76).wait(15));

	// felcha
	this.sig1 = new lib.CopiadeSímbolo1();
	this.sig1.setTransform(1056.9,722.1,1,1,0,0,0,40,40);
	new cjs.ButtonHelper(this.sig1, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.sig1).wait(39).to({_off:true},46).wait(15));

	// luces
	this.luz1 = new lib.Symbol26();
	this.luz1.setTransform(1056.9,722.8,0.727,0.727);
	this.luz1.shadow = new cjs.Shadow("rgba(204,255,0,1)",0,0,60);
	this.luz1.visible = false;

	this.timeline.addTween(cjs.Tween.get(this.luz1).wait(40).to({_off:true},45).wait(15));

	// panel
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF9966").s().p("EgqoAnEQirAAAAhxMAAAhKmQAAhwCrAAMBVRAAAQCrAAAABwMAAABKmQAABxirAAg");
	this.shape.setTransform(819.5,411.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},85).wait(15));

	// Capa 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2A6E7A").s().p("AhcBrQAAgLAIgHQAJgIAKAAQAFAAAJADQAIAEAIAAQAVAAAVgHQAYgHAHgKQgBgMglgRQgtgXgNgOQgNgQAAgTQAAgnAtgeQArgeAmAAQAmAAAAAhQAAAJgIAHQgJAHgGAAQgDAAgGgDQgGgEgEAAQgUAAgYAOQgWANAAASQAAAJAJAIQAGAJAbAMQAnAQAMAPQAMAPAAASQAAAhgsAWQgsAWg2AAQgoAAAAgeg");
	this.shape_1.setTransform(508,58.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#2A6E7A").s().p("AAsAsQg5BNg3AAQgUAAgOgQQgPgPAAgZQAAg8A1hBQA1hDA0AAQAbAAAJAbQAaAAAAAUQAAAKgFAYQgJAuAAAaQAAAdAEAMIAFAPQACAEAJAEQAJAEAAAHQAAAMgLAIQgMAHgNAAQgqAAAEhUgAgagdQgkAwAAAjQAAATAHAAQAbAAAlgvQAmgtAAgkQAAgLgFgGQgFgHgGAAQgXAAgiAyg");
	this.shape_2.setTransform(485.3,58.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#2A6E7A").s().p("AhOBvQgUgUAAgkQAAg3AuhBQAuhCArAAQAVAAAPAVQAPAVAAAXQAAAWgIAIQgIAHgHAAQgWAAgEgeQgCgWgJAAQgRAAgbAyQgdAwAAAlQAAAeAhAAQAiAAAlgZQARgNAKAAQANAAAAANQAAARgoAcQgoAcgpAAQglAAgTgVg");
	this.shape_3.setTransform(460.2,58.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#2A6E7A").s().p("Ag8COQAAgmALg3IAEgWQAHgoAAgFQAAgRAHgLQAHgLANAAQAOAAAIAHQAJAHAAAJQAAAJgJAaIgBAFQgKAsgDAbQgCAbAAARQAAAOAFAXIAAAHQAAAFgJAIQgKAJgMAAQgdAAAAgtgAAAiAQgLgLAAgLQAAgQALgKQAIgKATAAQAPAAAKAJQAJAJAAALQAAAQgOANQgPAMgKgBQgOAAgIgLg");
	this.shape_4.setTransform(444.3,53.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#2A6E7A").s().p("AhcBrQAAgLAIgHQAJgIAKAAQAFAAAJADQAIAEAIAAQAVAAAVgHQAYgHAHgKQgBgMglgRQgtgXgNgOQgNgQAAgTQAAgnAtgeQArgeAmAAQAmAAAAAhQAAAJgIAHQgJAHgGAAQgDAAgGgDQgGgEgEAAQgUAAgYAOQgWANAAASQAAAJAJAIQAGAJAbAMQAnAQAMAPQAMAPAAASQAAAhgsAWQgsAWg2AAQgoAAAAgeg");
	this.shape_5.setTransform(425.3,58.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#2A6E7A").s().p("AAsBsQg5BOg3AAQgUAAgPgQQgOgQAAgZQAAg7A1hDQA1hCA0AAQAbAAAJAcQAZAAAAAUQAAAJgFAXQgIAuAAAcQAAAcAEAMIAFAPQACAEAJAEQAJAEAAAIQAAALgMAIQgLAIgNAAQgqAAAEhVgAgaAiQgkAyAAAjQAAASAHAAQAbAAAlgvQAmgvAAgjQAAgJgFgHQgFgHgGAAQgXAAgiAxgAgIhTQgFgGAAgIQAAgNAegYIAAAAIAQgNQAngfAKgHQALgHAFAAQAGAAAHALQAHALAAAGQAAAFgGAHQgGAIgKAEQgKAFgZATQgFAFggAWIgOAKQgCABgEAAQgHAAgFgFg");
	this.shape_6.setTransform(402.6,52.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#2A6E7A").s().p("AhSC9QgQgKgBgPQgBgJgDgCIgFgGQgGgHgBgMQAAgOAIgsIAPhbQAViBAKgYQAJgYAYAAQATAAAAAhQAAAWgTBGQgJAjgPBEQAcgjAggXQAggXAaAAQAVAAAOASQAOASABAXQAABFg2A9Qg1A9g6AAQgSAAgPgKgAgWAyQgsA0AAAjQAJAPAMAAQAVAAAYgTQAZgUATgjQATgjAAgXQABgVgIAAQgjAAgrAzg");
	this.shape_7.setTransform(376.7,51.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#2A6E7A").s().p("AhcBrQAAgLAIgHQAJgIAKAAQAFAAAJADQAIAEAIAAQAVAAAVgHQAYgHAHgKQgBgMglgRQgtgXgNgOQgNgQAAgTQAAgnAtgeQArgeAmAAQAmAAAAAhQAAAJgIAHQgJAHgGAAQgDAAgGgDQgGgEgEAAQgUAAgYAOQgWANAAASQAAAJAJAIQAGAJAbAMQAnAQAMAPQAMAPAAASQAAAhgsAWQgsAWg2AAQgoAAAAgeg");
	this.shape_8.setTransform(333.9,58.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#2A6E7A").s().p("AhSBrQgVgYAAgqQAAg9Asg3QAtg3AwAAQAZAAAQAQQAPAQAAAWQAAAngmAjQglAig5ANQgHACAAAGQAAALAKAKQAJAJAQAAQAsAAAsguQAJgJAIAAQANAAAAAPQAAAXgnAhQgnAggwAAQgmAAgWgYgAgNg4QgYAdgIAeQAkgFAZgXQAbgXAAgTQAAgIgEgEQgEgGgHAAQgTAAgWAdg");
	this.shape_9.setTransform(312.9,58.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#2A6E7A").s().p("AgqC4QgGgQAAgkQAAhPAShoQAThsALgTQAKgTAPgBQAYAAAAAbQAAANgDANIgTBGQgLAogFAuQgGAvAAAbQAAAdAEAmIABAOQAAANgKAKQgIAKgLAAQgQAAgHgPg");
	this.shape_10.setTransform(295.9,52.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#2A6E7A").s().p("AAsAsQg5BNg3AAQgUAAgOgQQgPgPAAgZQAAg8A1hBQA1hDA0AAQAbAAAJAbQAaAAAAAUQAAAKgFAYQgJAuAAAaQAAAdAEAMIAFAPQACAEAJAEQAJAEAAAHQAAAMgLAIQgMAHgNAAQgqAAAEhUgAgagdQgkAwAAAjQAAATAHAAQAbAAAlgvQAmgtAAgkQAAgLgFgGQgFgHgGAAQgXAAgiAyg");
	this.shape_11.setTransform(274.2,58.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#2A6E7A").s().p("AhcBrQAAgLAIgHQAJgIAKAAQAFAAAJADQAIAEAIAAQAVAAAVgHQAYgHAHgKQgBgMglgRQgtgXgNgOQgNgQAAgTQAAgnAtgeQArgeAmAAQAmAAAAAhQAAAJgIAHQgJAHgGAAQgDAAgGgDQgGgEgEAAQgUAAgYAOQgWANAAASQAAAJAJAIQAGAJAbAMQAnAQAMAPQAMAPAAASQAAAhgsAWQgsAWg2AAQgoAAAAgeg");
	this.shape_12.setTransform(250.6,58.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#2A6E7A").s().p("Ag8COQAAgmALg3IAEgWQAHgoAAgFQAAgRAHgLQAHgLANAAQAOAAAIAHQAJAHAAAJQAAAJgJAaIgBAFQgKAsgDAbQgCAbAAARQAAAOAFAXIAAAHQAAAFgJAIQgKAJgMAAQgdAAAAgtgAAAiAQgLgLAAgLQAAgQALgKQAIgKATAAQAPAAAKAJQAJAJAAALQAAAQgOANQgPAMgKgBQgOAAgIgLg");
	this.shape_13.setTransform(237,53.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#2A6E7A").s().p("Ah0CEQgJgHAAgPQAAgOAMgVQAMgUAwgsIAMgLQgrg+AAgjQAAgmAhAAQAWAAACAiQABAiAYAlIAXgZIAHgIQAcgeANgXQAIgOAFgFQAFgEALAAQALAAAJAJQAIAIAAALQAAAZhpBcQAkAsAoAVIAKAHQABAFAAAFQAAALgJAJQgJAJgNgBQgiAAg6hPQgoAlgRAoQgHARgIAJQgTgBgKgHg");
	this.shape_14.setTransform(215.7,59.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#2A6E7A").s().p("AiICHQgegkAAgnQAAguAdg3QAcg5AsglQAsgkAvAAQAlAAAZAJQAYAJAVASQAUARAHATQAHASAAAhQAAAcgTAnQgSApgjAkQgjAkgkATQgiAVg7gBQgmAAgdgkgAg+hAQgvA/AAA7QAAAbARATQAQASAVAAQA7AAA0g6QA1g5AAg/QAAgXgJgOQgIgOgVgKQgVgJgYAAQgqAAguA+g");
	this.shape_15.setTransform(185.5,55.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#2A6E7A").s().p("AhcBrQAAgLAIgHQAJgIAKAAQAFAAAJADQAIAEAIAAQAVAAAVgHQAYgHAHgKQgBgMglgRQgtgXgNgOQgNgQAAgTQAAgnAtgeQArgeAmAAQAmAAAAAhQAAAJgIAHQgJAHgGAAQgDAAgGgDQgGgEgEAAQgUAAgYAOQgWANAAASQAAAJAJAIQAGAJAbAMQAnAQAMAPQAMAPAAASQAAAhgsAWQgsAWg2AAQgoAAAAgeg");
	this.shape_16.setTransform(138,58.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#2A6E7A").s().p("AhSBrQgVgYAAgqQAAg9Asg3QAtg3AwAAQAZAAAQAQQAPAQAAAWQAAAngmAjQglAig5ANQgHACAAAGQAAALAKAKQAJAJAQAAQAsAAAsguQAJgJAIAAQANAAAAAPQAAAXgnAhQgnAggwAAQgmAAgWgYgAgNg4QgYAdgIAeQAkgFAZgXQAbgXAAgTQAAgIgEgEQgEgGgHAAQgTAAgWAdg");
	this.shape_17.setTransform(117,58.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#2A6E7A").s().p("AgqC4QgGgQAAgkQAAhPAShoQAThsALgTQAKgTAPgBQAYAAAAAbQAAANgDANIgTBGQgLAogFAuQgGAvAAAbQAAAdAEAmIABAOQAAANgKAKQgIAKgLAAQgQAAgHgPg");
	this.shape_18.setTransform(100,52.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#2A6E7A").s().p("AAsAsQg5BNg3AAQgUAAgOgQQgPgPAAgZQAAg8A1hBQA1hDA0AAQAbAAAJAbQAaAAAAAUQAAAKgFAYQgJAuAAAaQAAAdAEAMIAFAPQACAEAJAEQAJAEAAAHQAAAMgLAIQgMAHgNAAQgqAAAEhUgAgagdQgkAwAAAjQAAATAHAAQAbAAAlgvQAmgtAAgkQAAgLgFgGQgFgHgGAAQgXAAgiAyg");
	this.shape_19.setTransform(78.3,58.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#2A6E7A").s().p("Ah1CmQgOgKAAgOQAAgMAGgJQAHgJAIAAQAGgBAEACQAYAKAUAAQAjAAAqgUQAsgTAAgTQAAgIgLgHQgLgHghgMQgvgPgZgLQgYgIgNgRQgNgQAAgYQAAgqAxgkQAxgkBAAAQAmgBAWAQQAWAOAAAUQAAAogrAAQAAgWgMgJQgLgJgXAAQglAAgfASQggATAAAWQAAAOAMALQAMAJAxAPQA2AQAaAQQAZATAAAaQAAArhCAkQhAAlhHAAQgXAAgOgKg");
	this.shape_20.setTransform(50.5,55.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).to({state:[]},85).wait(15));

	// fondo
	this.instance_8 = new lib.FONDOFLASH();

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({_off:true},85).wait(15));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(580,393,1163.9,829.8);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;